Remove unused oj files and codes
skku-npc/skku-coding-platform pull request #102
Opened 2021-06-15 06:21 UTC by jimin9038

Remove unused oj page code
- Remove APIs of unused oj files
- Remove unused files: help/*, rank/*, contest/children/* , UserHome.vue
- Remove code importing unused files from router/routes.js, views/index.js and views/contest/index.js
- Fix typo from Announcement.vue
- Fix jsDOCs from api.js
- Remove unused code from CodeMirror.vue, AnnouncementList.vue, ContestDetail.vue, and Header.vue

2021-06-15 07:12 UTC, dotoleeoak requested changes
problem/chartData.js도 지우기 ✅

2021-06-15 07:12 UTC, dotoleeoak commented on frontend/src/pages/oj/views/announcement/Announcement.vue
> +    <div class="announcement_header">
class 이름 고친 이유는?

2021-06-15 08:52 UTC, jimin9038 commented on frontend/src/pages/oj/api.js
> -  },
반영하였음

2021-06-15 08:53 UTC, jimin9038 commented on frontend/src/pages/oj/views/announcement/Announcement.vue
> +    <div class="announcement_header">
annoucement의 typo가 틀린 것 같아 annoucement -> announcement로 바꿈, 다만 언더라인이 하나 부족하여 announcement__header로 다시 반영함

2021-06-16 04:17 UTC, dotoleeoak commented
oj/views/settings에서 Settings.vue랑 ProfileSetting.vue 묶을 수 있을텐데, ProfileSetting.vue 한 파일로 정리한 다음 oj/views/user 폴더로 옮겨봐

2021-06-16 06:48 UTC, Jeongcc approved these changes

2021-06-16 09:18 UTC, dotoleeoak commented
chartData.js에 쓰였던 패키지인 `ECharts` 지우기 (index.js, package.json 등 수정)

2021-06-16 09:21 UTC, dotoleeoak commented
oj/views에서 contest에만 index.js가 있는데, contest에서도 index.js 지울 수 있으면 지우기 (못 지우는 이유 있으면 알려주세요)

2021-06-16 22:18 UTC, dotoleeoak approved these changes

2021-06-16 23:54 UTC, merged