Delete unused apis 2
skku-npc/skku-coding-platform pull request #111
Opened 2021-06-21 00:26 UTC by joft-ware

checkUsernameOrEmail 
        (살려두기로 함)

freshDisplayID (userID) - UserHome.vue - Deleted | 'api/profile/fresh_display_id', 'get'  
	account>urls>oj.py - profile/fresh_display_id url 삭제
	account>views>oj.py - ProfileProblemDisplayIDRefreshAPI 클래스 삭제

twoFactorAuth (method, data) - No use - Deleted | 'api/two_factor_auth', -
	account>urls>oj.py - two_factor_auth url 삭제
	account>views>oj.py - TwoFactorAuthAPI 클래스 삭제
	account>serializers.py - TwoFactorAuthCodeSerializer 클래스 삭제
	account>tests.py - TwoFactorAuthAPITest 클래스 삭제

tfaRequiredCheck (username) - No use - Deleted | 'api/tfa_required', 'post'
	account>urls>oj.py - tfa_required url 삭제
	account>views>oj.py - CheckTFARequiredAPI 클래스 삭제
	account>tests.py - TFARequiredCheckAPITest 클래스 삭제

getSessions () - No use (Admin에서는 사용됨) - Deleted | 'api/sessions', 'get'
	account>urls>oj.py - sessions url 삭제
	account>views>oj.py - SessionManagementAPI 클래스 삭제(get, delete 메소드 둘 다 사용되지 않음)
	account>tess.py - SessionManagementAPITest 클래스 삭제

2021-06-21 10:01 UTC, dotoleeoak requested changes
`src/locust`는 무슨 파일인가요?

2021-06-21 10:17 UTC, joft-ware commented
> `src/locust`는 무슨 파일인가요?

앗 load test용으로 쓰던 건데 잘못 올라갔네요 삭제하겠슴다

2021-06-21 18:30 UTC, 22222bh approved these changes
수고하셨습니다.
머지하고 브랜치 삭제해주세요!

2021-06-21 18:31 UTC, 22222bh approved these changes
재민이가 말한 src/locust 삭제된 것 확인했습니다

2021-06-25 17:20 UTC, Jeongcc commented
테스트 실패 확인해주세용 @joft-ware

2021-06-27 00:44 UTC, dotoleeoak approved these changes
이거 하나만 고치고 merge 해주세요

2021-06-27 00:44 UTC, dotoleeoak commented on backend/account/views/oj.py
> -import qrcode
`requirements.txt`에서도 `qrcode` module 지워줍시다

2021-06-27 01:36 UTC, dotoleeoak commented
`dev/deprecated_api`, `user/jaehun` 브랜치 rebase 했습니다

2021-06-27 06:00 UTC, merged

2021-06-27 06:08 UTC, dotoleeoak commented
@joft-ware `requirements.txt`에서 `qrcode` 모듈 아직 안지우지 않았나요?

2021-06-27 06:29 UTC, joft-ware commented
아 확인을 못했네요 다시 PR 올리겠습니다