async, await 처리
skku-npc/skku-coding-platform pull request #115
Opened 2021-06-22 13:01 UTC by SOLBI1028

admin(contest, general)
oj(announcement, contest, general)

2021-06-27 04:21 UTC, dotoleeoak commented
`dev/async`에 rebase 했습니다

2021-06-27 05:54 UTC, dotoleeoak requested changes

2021-06-27 05:54 UTC, dotoleeoak commented on frontend/src/pages/admin/views/contest/ContestList.vue
>            (res) => {
```javascript
this.loading = true
try {
  const res = await api.getContestList((page - 1) * this.pageSize, this.pageSize, this.keyword)
  this.total = res.data.data.total
  this.contestList = res.data.data.results
} catch(err) {
} finally {
  this.loading = false
}
```

2021-06-27 05:54 UTC, dotoleeoak commented on frontend/src/pages/admin/views/general/Announcement.vue
>        })
이 부분도 위랑 비슷하니까 직접 고쳐보셔요

2021-06-27 05:54 UTC, dotoleeoak commented on frontend/src/pages/admin/views/general/Announcement.vue
>        }).catch(() => {
여기도!

2021-06-27 05:54 UTC, dotoleeoak commented on frontend/src/pages/admin/views/general/Announcement.vue
>        }).catch()
```javascript
try {
  const res= api[funcName](data)
  this.showEditAnnouncementDialog = false
  await this.init()
} catch (err) {
}
```

2021-06-27 05:54 UTC, dotoleeoak commented on frontend/src/pages/admin/views/general/Announcement.vue
>          this.loading = false
```javascript
deleteAnnouncement (announcementId) {
  try {
    await this.$confirm('Are you sure you want to delete this announcement?', 'Warning', {
      confirmButtonText: 'Delete',
      cancelButtonText: 'Cancel',
      type: 'warning'
    })
    this.loading = true
    const funcName = this.contestID ? 'deleteContestAnnouncement' : 'deleteAnnouncement'
    await api[funcName](announcementId)
    this.loading = true
    await this.init()
  } finally {
    this.loading = false
  }
},
```

2021-06-27 05:54 UTC, dotoleeoak commented on frontend/src/pages/admin/views/general/Conf.vue
>        }
```javascript
const res = await api.getSMTPConfig()
if (res.data.data) {
...
```

2021-06-27 05:54 UTC, dotoleeoak commented on frontend/src/pages/admin/views/general/Conf.vue
> +    await api.getWebsiteConfig().then(res => {
```javascript
try {
  const res = await api.getWebsiteConfig()
  this.websiteConfig = res.data.data
} catch {
}
```

2021-06-27 05:54 UTC, dotoleeoak commented on frontend/src/pages/admin/views/general/Conf.vue
>          })
```javascript
try {
  await api.editSTMPConfig(this.smtp)
  this.saved = true
} catch (err) {
}
```

2021-06-27 05:54 UTC, dotoleeoak commented on frontend/src/pages/admin/views/general/Conf.vue
>        })
```javascript
try {
  const value = await this.$prompt('Please input your email', '', {
    inputPattern: /[\w!#$%&'*+/=?^_`{|}~-]+(?:\.[\w!#$%&'*+/=?^_`{|}~-]+)*@(?:[\w](?:[\w-]*[\w])?\.)+[\w](?:[\w-]*[\w])?/,
    inputErrorMessage: 'Error email format'
  })
  this.loadingBtnTest = true
  try {
    await api.testSMTPConfig(value)
  } catch (err) {
  } finally {
    this.loadingBtnTest = false
  }
} catch (err) {
}
```

2021-06-27 05:54 UTC, dotoleeoak commented on frontend/src/pages/admin/views/general/Conf.vue
>        })
```javascript
async saveWebsiteConfig() {
  try {
    await api.editWebsiteConfig(this.websiteConfig)
  } catch (err) {
  }
}

2021-06-27 05:54 UTC, dotoleeoak commented on frontend/src/pages/admin/views/general/Dashboard.vue
>      })
```javascript
try {
  const res = await api.getDashboardInfo()
  this.infoData = res.data.data
} catch (err) {
}
```

2021-06-27 05:54 UTC, dotoleeoak commented on frontend/src/pages/admin/views/general/Dashboard.vue
>      })
이제 여기도 어떻게 고쳐야 할지 알거라고 믿습니다...ㅎㅎ

2021-06-27 05:54 UTC, dotoleeoak commented on frontend/src/pages/admin/views/general/Dashboard.vue
> +    await api.getReleaseNotes().then(resp => {
혹시 모르겠으면 말씀 주세요

2021-06-27 05:54 UTC, dotoleeoak commented on frontend/src/pages/oj/views/announcement/Announcement.vue
> +      await api.getAnnouncementDetail(this.$route.params.announcementID).then(res => {
~~

2021-06-27 05:54 UTC, dotoleeoak commented on frontend/src/pages/oj/views/announcement/AnnouncementList.vue
> +      await api.getAnnouncementList((page - 1) * this.limit, this.limit).then(res => {
~~\~

2021-06-27 05:54 UTC, dotoleeoak commented on frontend/src/pages/oj/views/announcement/AnnouncementList.vue
> +      await api.getContestAnnouncementList(this.$route.params.contestID).then(res => {
`.then` 들어간 부분은 다 없애야 된다고 생각하시면 됩니다

2021-06-27 05:54 UTC, dotoleeoak commented on frontend/src/pages/oj/views/contest/ContestDetail.vue
> +    await this.$store.dispatch('getContest').then(res => {
~~\~~

2021-06-27 05:54 UTC, dotoleeoak commented on frontend/src/pages/oj/views/contest/ContestDetail.vue
> +      await api.checkContestPassword(this.contestID, this.contestPassword).then((res) => {
~~\~~\~

2021-06-27 05:54 UTC, dotoleeoak commented on frontend/src/pages/oj/views/contest/ContestList.vue
> +      await api.getContestList(offset, this.limit, this.query).then((res) => {
~~\~~\~~

2021-06-29 10:02 UTC, dotoleeoak requested changes

2021-06-29 10:02 UTC, dotoleeoak commented on frontend/src/pages/oj/views/contest/ContestDetail.vue
>          const data = res.data.data
@SOLBI1028 이 부분 확인 부탁드려요~

2021-06-30 12:03 UTC, SOLBI1028 commented
수정해야할 부분 수정했습니다..!

2021-06-30 12:14 UTC, dotoleeoak commented
내일 확인해볼게욤

2021-07-01 11:49 UTC, dotoleeoak requested changes
이거 하나만 마지막으로 고쳐주세요...!

2021-07-01 11:49 UTC, dotoleeoak commented on frontend/src/pages/admin/views/general/Announcement.vue
>          const funcName = this.contestID ? 'deleteContestAnnouncement' : 'deleteAnnouncement'
```js
try {
  await this.$confirm(...)
  this.loading = true
  const funcName = ...
...

2021-07-01 12:45 UTC, Jeongcc approved these changes

2021-07-01 13:49 UTC, merged