admin(problem)
skku-npc/skku-coding-platform pull request #117
Opened 2021-06-23 10:58 UTC by Anzanda

oj(user)

2021-06-25 17:23 UTC, Jeongcc commented on frontend/src/pages/oj/views/user/Register.vue
> -      ]
윤성아 여기 왜 지운거야 ?

2021-06-27 07:10 UTC, dotoleeoak requested changes
`ProblemList.vue`, `ProfileSetting.vue`, `Register.vue`, `ResetPassword.vue`
위 4개 파일들은 수정 내용이 너무 많아서 일단 보류했고 나중에 다시 리뷰할게.
async-await 처리는 대부분 잘 했는데, 내가 `ProblemList.vue`에 커멘트 단 대로 앞으로는 커밋하는 내용 신경써서 할 수 있도록! [같이 올린 글](https://tech.10000lab.xyz/git/git-commit-discipline.html) 꼭 한번 읽어봐

2021-06-27 07:10 UTC, dotoleeoak commented on frontend/src/pages/admin/views/problem/Problem.vue
> +        }
`try-catch` 넣기

2021-06-27 07:10 UTC, dotoleeoak commented on frontend/src/pages/admin/views/problem/ProblemList.vue
> +        mode="out-in"
**앞으로는 구현 기능마다 나눠서 커밋하기 & pr 올릴 때 관련된 커밋만 올리기...
이렇게 몇 백 줄을 한 번에 커밋/pr 올리면 리뷰가 어려워짐...ㅠ**

2021-06-27 07:10 UTC, dotoleeoak commented on frontend/src/pages/admin/views/problem/ProblemList.vue
> +        mode="out-in"
관련 글: https://tech.10000lab.xyz/git/git-commit-discipline.html

2021-06-27 07:10 UTC, dotoleeoak commented on frontend/src/pages/admin/views/problem/ProblemList.vue
> +        mode="out-in"
git은 훗날 과거의 수정 기록을 참고하기 위한 것이니까, 나중에 커밋을 다시 읽어볼 때 쉽게 수정 내용을 이해할 수 있도록 커밋해야 함...!

2021-06-27 07:10 UTC, dotoleeoak commented
그리고 import 잘못된 거 있는거 같은데 test 내용 확인해보고 수정해줘

2021-06-27 07:18 UTC, Anzanda commented on frontend/src/pages/admin/views/problem/Problem.vue
> +      this.testCaseUploaded = true
![image](https://user-images.githubusercontent.com/79851762/123536103-45571080-d763-11eb-8ecb-67a887480d83.png)

2021-06-27 07:21 UTC, dotoleeoak commented on frontend/src/pages/admin/views/problem/Problem.vue
> +      this.testCaseUploaded = true
사진에 있는건 커밋 전 내용 같은데?

2021-06-27 07:24 UTC, Anzanda commented on frontend/src/pages/admin/views/problem/Problem.vue
> +        }
![image](https://user-images.githubusercontent.com/79851762/123536230-19885a80-d764-11eb-9889-7abca40bde03.png)

2021-06-27 09:56 UTC, Anzanda commented on frontend/src/pages/admin/views/problem/Problem.vue
> +      this.testCaseUploaded = true
아항 사진은 커밋 전 내용 저장용 ㅋㅎㅋ 보면서 고치려고 첨부했는데 담부턴 안할게용

2021-06-27 17:48 UTC, Jeongcc approved these changes

2021-06-29 09:37 UTC, dotoleeoak requested changes

2021-06-29 09:45 UTC, dotoleeoak commented on frontend/src/pages/admin/views/problem/AddPublicProblem.vue
> +      }
try-catch 한번만 써도 됩니다
```js
// line 99
try {
  const value = await this.$prompt(...)
  const data = ...
  await api.addProblemFromPublic(data)
  this.$emit('on-change')
} catch (err) {
}

2021-06-29 09:46 UTC, dotoleeoak commented on frontend/src/pages/admin/views/problem/AddPublicProblem.vue
> +      }
`Promise.catch()`와 다르게 `try-catch` 구문은 `try` 코드블럭 전체의 에러를 handling하기 때문에 하나의 try-catch만 써도 됩니다

2021-07-01 10:36 UTC, Jeongcc approved these changes

2021-07-01 10:39 UTC, merged