Dev/tiptap
skku-npc/skku-coding-platform pull request #127
Opened 2021-06-27 19:18 UTC by jimin9038

Apply Tiptap Editor 
- Delete simditor and related dependencies
- Tiptap Editor Design using Bootstrap-vue 
- Inserting link/Image/File available
![image](https://user-images.githubusercontent.com/73051219/123556658-66514d00-d7c7-11eb-869f-95be382c7d8e.png)
![image](https://user-images.githubusercontent.com/73051219/123556684-913ba100-d7c7-11eb-84b7-3764dbd84ba0.png)

2021-06-27 19:22 UTC, jimin9038 commented
Tiptap Editor에 들어간 Code, Horizontal Rule, Quote 등은 Problem 페이지나 Contest 페이지에서 잘 보이지 않아 수정 예정입니다.

2021-06-28 13:48 UTC, Jeongcc commented
Announcement에서 Insert from file 시 모달이 뒤에 뜨는 문제

2021-06-28 16:25 UTC, jimin9038 commented
problem description 과 contest description에 Tiptap에디터에서 지원하는 수평선, 인용문, 코드 블럭 등의 css 적용 예정

2021-06-28 16:25 UTC, jimin9038 commented
Simditor에서는 gif 가 업로드되는데  Tiptap에서는 gif가 업로드가 되지 않음

2021-06-30 15:41 UTC, jimin9038 commented
admin/components의 Tiptap.vue 가보시면, ProseMirror맨 아래에 제가 ul,ol, h3, h4, code, pre 등 에디터에 들어갈 다양한 태그의 css를 설정해두었습니다. 이를 참고하여 oj의 Annoucement.vue, Problem.vue, Contest.vue에서 tiptap editor로 작성할 수 있는 부분인 아래의 것들을 Tiptap 에디터에 작성했을 때 oj페이지에서도 모두 보이도록 css를 수정해주세요! 

bold
Italic
Strike
Code
Clear Mark
H1
H2
Paragraph
These are One Paragraph
Line Break Shortcut: shift+ enter
Paragraph Break Shortcut: enter
Unordered List
22
dafdafasdf
Double enter to escape from list
Ordered List
222
Double enter to escape from list
Code block
HAHAHA
Ctrl Enter / Shift Enter to Hard break
This is Block Quote
Double enter to escape
Horizontal rule ----
-- Horizontal Rule
Redo / Undo available
Link ---
Add Link
---Link
Insert Image from URL
Upload Image From Local
KakaoTalk_20180802_142209072.jpg
Upload File From Local

2021-06-30 17:13 UTC, Jeongcc commented
problem description과 contest description에 Tiptap 에디터에서 지원하는 수평선, 인용문, 코드 블럭 등의 css 적용 (경환님이 7/2 금요일까지 예정)

dev/bootstrapvue 머지 이후에 
Announcement에서 Insert from file 시 모달이 뒤에 뜨는 문제 확인하기

+) gif 문제는 지민이가 7/2 금요일까지 병행해서 보기로 함

2021-07-02 17:34 UTC, Jeongcc commented
![image](https://user-images.githubusercontent.com/46365350/124310401-15669d80-dba7-11eb-8345-0ba4c2f8f6d8.png)
이미지 업로드가 안 되는데 다시 확인 부탁드려요 :) @jimin9038

2021-07-03 09:42 UTC, jimin9038 commented
> Simditor에서는 gif 가 업로드되는데 Tiptap에서는 gif가 업로드가 되지 않음

gif만 안되는 것이 아니라 이미지, 파일 모두 2.5MB 이상은 업로드가 되지 않습니다. Simditor에서는 그 이상도 업로드가 됐으나 Tiptap에서는 업로드가 되지 않네요.  Django default upload size가 2.5MB라고 하니 이와 관련된 문제로 보이긴 하는데 기존의 api를 활용했음에도 불구하고 왜 simditor에서는 되고 tiptap에서는 안 되는지 알 수 없어 더 찾아봐야 할 것 같습니다. 일단은 업로드 창에서 2.5MB이상의 이미지와 파일은 업로드할 수 없다고 문구를 붙여놓았습니다.

2021-07-03 11:20 UTC, dotoleeoak commented
https://stackoverflow.com/questions/56982999/how-to-upload-file-larger-than-2-5mb-to-django
이걸로 해결 되나요?

2021-07-03 11:22 UTC, dotoleeoak commented
`master` -> `dev` 브랜치로 merge는 자제하길 바랍니다.
가능한 `git rebase master` 명령어로 rebase하는걸 권합니다.

2021-07-03 11:28 UTC, dotoleeoak commented
merge한 커밋은 삭제하고, master에 rebase 해주세요.

```bash
# Update master branch
git switch master
git pull

# Delete merge commit
git switch dev/tiptap
git pull
git reset --hard HEAD^

# Push to remote
git push --force-with-lease

2021-07-03 12:52 UTC, jimin9038 commented
/home/silentstorm/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.3/dist/bundled/stubs/django/conf/global_settings.pyi 에 DATA_UPLOAD_MAX_MEMORY_SIZE = 50242880로 설정하고 테스트 해봤으나 해결되지 않습니다. 혹시 settings.py라는 게 이 path를 말하는 것이 아니거나, 코드를 적용하기 위해서 별다른 처리가 필요한 것은 아니지요?

2021-07-04 00:05 UTC, dotoleeoak commented
@jimin9038 그 경로가 아니라 `backend/oj/settings.py`에 추가하는게 맞습니다. 
다 되면 `backend/`에서 `docker cp oj coding-platform:/app` 명령어로 컨테이너에 올리고, 
`docker restart coding-platform` 명령어로 재시작하면 됩니다.

2021-07-04 00:56 UTC, dotoleeoak requested changes

2021-07-04 00:56 UTC, dotoleeoak commented on frontend/package.json
> +    "tiptap": "^1.32.2",
이 줄은 지우는게 좋을 것 같네요

2021-07-04 00:56 UTC, dotoleeoak commented on frontend/src/pages/admin/components/Tiptap.vue
> +    }
굳이 `isSame` 변수를 정의할 필요가 없지 않나요?
```js
if (this.editor.getHTML() !== value) {
  this.editor.commands.setContent(this.value, false)
}

2021-07-04 00:56 UTC, dotoleeoak commented on frontend/src/pages/admin/components/Tiptap.vue
> +    openImageModal: function () {
이 문법으로 쓴 이유가 뭔가요?
```js
openImageModal: function () { ... }
function openImageModal() { ... }

2021-07-04 00:56 UTC, dotoleeoak commented on frontend/src/pages/admin/components/Tiptap.vue
> +          <b-button size="sm" title="Heading 4" type="button" variant="outline-dark" @click="editor.chain().focus().toggleHeading({ level: 4 }).run()" class="EditorButton" :class="{ 'is-active': edit
`Heading 3`, `Heading 4`는 의도한건가요, 오타인가요?

2021-07-04 00:56 UTC, dotoleeoak commented on frontend/src/pages/admin/views/general/Announcement.vue
> +          <Tiptap v-model="announcement.content" />
Contest.vue에 맞춰서 소문자로 합시다 `Tiptap` => `tiptap`

2021-07-04 00:56 UTC, dotoleeoak commented on frontend/src/pages/admin/views/problem/Problem.vue
> +              <Tiptap v-model="problem.description"></Tiptap>
여기도 전부 소문자로 고치는게 낫겠네요
> The name you give a component may depend on where you intend to use it. When using a component directly in the DOM (as opposed to in a string template or single-file component), we strongly recommend following the W3C rules for custom tag names **(all-lowercase, must contain a hyphen)**. This helps you avoid conflicts with current and future HTML elements.

https://vuejs.org/v2/guide/components-registration.html#Component-Names

2021-07-04 00:56 UTC, dotoleeoak commented on frontend/src/pages/admin/views/problem/Problem.vue
> +          <Tiptap v-model = "problem.hint" placeholder=""></Tiptap>
사소한거지만 같이 고쳐주세요
```
v-model = "problem.hint"
v-model="problem.hint"
```

2021-07-04 00:56 UTC, dotoleeoak commented on frontend/src/pages/oj/views/problem/Problem.vue
> +
TitTap 관련 style은 `styles` 폴더에 별도의 scss 파일로 정의해서, 여러 component에서 공유하는게 낫겠네요

2021-07-04 04:17 UTC, jimin9038 commented on frontend/src/pages/admin/components/Tiptap.vue
> +          <b-button size="sm" title="Heading 4" type="button" variant="outline-dark" @click="editor.chain().focus().toggleHeading({ level: 4 }).run()" class="EditorButton" :class="{ 'is-active': edit
실제로는 Heading 3, 4로 설정되나 tiptap 아이콘이 H3,H4로 들어가면 이상해 아이콘만 H1, H2로 넣었습니다

2021-07-04 04:33 UTC, dotoleeoak commented on frontend/src/pages/admin/components/Tiptap.vue
> +          <b-button size="sm" title="Heading 4" type="button" variant="outline-dark" @click="editor.chain().focus().toggleHeading({ level: 4 }).run()" class="EditorButton" :class="{ 'is-active': edit
Title 값은 heading 1, 2로 설정하고 실제 적용 값은 heading 3, 4로 하는거 어떤가요?

2021-07-04 05:02 UTC, jimin9038 commented on frontend/src/pages/admin/components/Tiptap.vue
> +          <b-button size="sm" title="Heading 4" type="button" variant="outline-dark" @click="editor.chain().focus().toggleHeading({ level: 4 }).run()" class="EditorButton" :class="{ 'is-active': edit
네 title은 커서 올렸을 때 보이니 그렇게 하면 좋을 것 같네요

2021-07-04 07:09 UTC, jimin9038 commented
> @jimin9038 그 경로가 아니라 `backend/oj/settings.py`에 추가하는게 맞습니다.
> 다 되면 `backend/`에서 `docker cp oj coding-platform:/app` 명령어로 컨테이너에 올리고,
> `docker restart coding-platform` 명령어로 재시작하면 됩니다.

해결되었습니다!

2021-07-04 07:11 UTC, jimin9038 commented on frontend/src/pages/oj/views/problem/Problem.vue
> +
가독성이 좀 안 좋긴 하지만 style이 사용하는 곳마다 다른 부분이 있어 굳이 한 파일로 안 묶는게 나을 것 같습니다.

2021-07-04 10:23 UTC, dotoleeoak commented
> 근데 파일 메모리 최대 사이즈 50242880으로 하면 너무 많으려나요..

50MB 정도면 적당한 것 같네요

2021-07-04 10:32 UTC, dotoleeoak approved these changes
하나만 확인 부탁드려요~

2021-07-04 10:32 UTC, dotoleeoak commented on backend/oj/settings.py
> +FILE_UPLOAD_MAX_MEMORY_SIZE = 50242880
https://stackoverflow.com/questions/60429218/django-file-upload-max-memory-vs-data-upload-max-memory
`FILE_UPLOAD_MAX_MEMORY_SIZE`는 cache 크기라서 빼도 될 것 같네요.

(`DATA~`: request의 최대 크기, `FILE~`: 한번에 메모리에 올라갈 수 있는 파일 크기
즉, `FILE~`보다 request가 크면 임시 파일로 저장한 다음 `FILE~` 크기로 나눠서 처리하는 것 같네요)

2021-07-04 10:33 UTC, dotoleeoak commented on frontend/src/pages/oj/views/problem/Problem.vue
> +
다른 부분이 많으면 이대로 해도 좋긴 한데, 공통되는 부분이 많으면 일단 하나의 scss 파일에 정의하고, 각 vue 파일마다 추가적인 style을 정의하는 게 낫지 않나요?

2021-07-04 10:33 UTC, dotoleeoak commented on frontend/src/pages/oj/views/problem/Problem.vue
> +
뭐 다른 component들도 scss 정리할 건 많으니까 나중에 한번에 하는걸로 할게요

2021-07-04 10:35 UTC, dotoleeoak commented
위에 사항 고치고 master에 rebase한 다음 merge해주세요

2021-07-04 12:18 UTC, merged