merge dev/async
skku-npc/skku-coding-platform pull request #136
Opened 2021-07-01 14:23 UTC by SOLBI1028

dev/async 브랜치를 master로 merge

2021-07-02 14:45 UTC, dotoleeoak approved these changes

2021-07-02 14:45 UTC, dotoleeoak commented on frontend/src/pages/admin/views/general/Conf.vue
> +      }
여기 try-catch 한 쌍으로 고칠 수 있겠네요
```js
try {
  const { value } = await this.$prompt('Please input your email', '', {
    inputPattern: /[\w!#$%&'*+/=?^_`{|}~-]+(?:\.[\w!#$%&'*+/=?^_`{|}~-]+)*@(?:[\w](?:[\w-]*[\w])?\.)+[\w](?:[\w-]*[\w])?/,
    inputErrorMessage: 'Error email format'
  })
  this.loadingBtnTest = true
  await api.testSMTPConfig(value)
} catch (err) {
} finally {
  this.loadingBtnTest = false
}

2021-07-02 14:45 UTC, dotoleeoak commented on frontend/src/pages/admin/views/general/Conf.vue
>        }
여기는 이렇게 고치는게 낫겠네요
```js
// line 205~
try {
  const funcName = this.init ? "createSMTPConfig" : "editSMTPConfig"
  await api[funcName](this.smtp)
  this.saved = true
} catch (err) {
}

2021-07-02 14:45 UTC, dotoleeoak commented on frontend/src/pages/admin/views/general/User.vue
> +      } catch (res) {
변수명 `res` => `err`로 고쳐주세요

2021-07-02 14:45 UTC, dotoleeoak commented on frontend/src/pages/admin/views/general/User.vue
> +      }
try-catch는 다중으로 쓰는 것보단, 각 부분을 나눠서 쓰는게 낫습니다
```js
try {
  await this.$confirm(...)  // don't forget `await`
} catch (err) {
}
try {
  await api.deleteUsers(ids.join(','))
} catch (err) {
} finally {
  await this.getUserList(this.currentPage)
}

2021-07-02 14:45 UTC, dotoleeoak commented on frontend/src/pages/admin/views/problem/Problem.vue
> +      const problemRes = await api[funcName](this.$rout.params.problemId)
`$rout` => `$route`

2021-07-02 14:45 UTC, dotoleeoak commented on frontend/src/pages/admin/views/problem/Problem.vue
> +      else this.problem.spj = false
```js
// line 431 ~ 432
this.problem.spj = testcaseData.spj === 'True'

2021-07-02 14:45 UTC, dotoleeoak commented on frontend/src/pages/admin/views/problem/Problem.vue
> +          if (this.routeName === 'create-contest-problem' || this.routeName === 'edit-contest-problem') {
꼭 고칠 필요는 없는데 이렇게 고쳐봐도 될 듯...?
```js
// line 683
if (['create-contest-problem', 'edit-contest-problem'].includes(this.routeName)) { ... }

2021-07-02 14:45 UTC, dotoleeoak commented on frontend/src/pages/admin/views/problem/Problem.vue
>            if (this.routeName === 'create-contest-problem' || this.routeName === 'edit-contest-problem') {
위랑 마찬가지

2021-07-02 14:45 UTC, dotoleeoak commented on frontend/src/pages/oj/views/problem/Problem.vue
> +          this.addStatusColumn(this.ACMTableColumns, res.data.data)
Line 320, 322 같은 내용인데 Line 319, 321은 or 조건으로 묶어도 되겠네요

2021-07-02 14:45 UTC, dotoleeoak commented on frontend/src/pages/oj/views/submission/SubmissionList.vue
> +      } catch (res) {
`res` => `err`로 변수명 바꿔주세요

2021-07-02 14:45 UTC, dotoleeoak commented on frontend/src/pages/oj/views/user/ProfileSetting.vue
> +    this.formProfile.language = infoRes.data.data.language
`api.getUser`이랑 `api.getUserInfo`는 parallel하게 이뤄져야 돼서 아래처럼 코드 고쳐주세요
(문법 맞는지 확실하진 않아서 혹시 잘못된거 있으면 알려주세요)
```js
const [res, infoRes] = await Promise.all([api.getuser(user.username), api.getUserInfo(user.username)])

2021-07-02 14:45 UTC, dotoleeoak commented on frontend/src/pages/oj/views/user/ProfileSetting.vue
>          this.loading.btnLanguage = false
Line 160에 `this.loading.btnLanguage = false`를 지워야 `finally` 구문이 의미가 있겠죠?

2021-07-02 14:45 UTC, dotoleeoak commented on frontend/src/pages/oj/views/user/ProfileSetting.vue
> +        if (err.data.data === 'tfa_required') {
문법이 맞는지 모르겠는데 동작 잘 되는지 확인했나요?
`catch (err)`에서 `err`에는 Error 객체가 넘어오지 않나요?

2021-07-03 00:22 UTC, dotoleeoak commented
실수로 approvr로 했는데 위에 사항들 반영해주세요

2021-07-03 04:37 UTC, dotoleeoak commented
브랜치 rebase했습니다

2021-07-03 09:54 UTC, Anzanda commented on frontend/src/pages/admin/views/problem/Problem.vue
> +          if (this.routeName === 'create-contest-problem' || this.routeName === 'edit-contest-problem') {
좀 더 깔끔하네요 좋은 의견 감사합니다.

2021-07-03 09:56 UTC, Anzanda commented on frontend/src/pages/admin/views/problem/Problem.vue
>            if (this.routeName === 'create-contest-problem' || this.routeName === 'edit-contest-problem') {
이것도 코드컨벤션이나 클린코드에 나온 내용인가요?

2021-07-03 09:58 UTC, Anzanda commented on frontend/src/pages/oj/views/user/ProfileSetting.vue
>          this.loading.btnLanguage = false
앗 ㅋㅋ 넵 부끄

2021-07-03 10:19 UTC, Anzanda commented on frontend/src/pages/oj/views/user/ProfileSetting.vue
> +        if (err.data.data === 'tfa_required') {
https://www.notion.so/coding1398/Async-await-reject-e5befadf5c46422faf91bfacfbcfd3aa
위 링크에 정리해봤습니다. async/await를 try~catch로 처리할 때 cathc의 인자에는 reject일 때의 반환된 것이 담깁니다.

2021-07-03 10:20 UTC, Anzanda commented on frontend/src/pages/oj/views/user/ProfileSetting.vue
> +        if (err.data.data === 'tfa_required') {
읽어보시고 피드백 부탁드려요ㅎㅎ

2021-07-03 10:28 UTC, Anzanda commented on frontend/src/pages/oj/views/user/ProfileSetting.vue
> +    this.formProfile.language = infoRes.data.data.language
문법 정확합니다. 감사합니다.

2021-07-03 12:04 UTC, dotoleeoak commented on frontend/src/pages/oj/views/user/ProfileSetting.vue
> +        if (err.data.data === 'tfa_required') {
그러니까 reject로 받아지는 것이 Error 객체 아닌가요? `.data.data` 속성을 받아오려면 `err` 변수가 Request 객체여야할텐데 말이죠.

2021-07-03 12:05 UTC, dotoleeoak commented on frontend/src/pages/oj/views/user/ProfileSetting.vue
> +        if (err.data.data === 'tfa_required') {
https://stackoverflow.com/questions/45017822/catching-error-body-using-axios-post

찾아보니까 axios에서 reject로 return하는 객체에서 `err.response.data` 형식으로 response body에 접근할 수 있는 것 같습니다. 더 찾아보고 수정해주세요

2021-07-03 12:09 UTC, dotoleeoak commented on frontend/src/pages/oj/views/user/ProfileSetting.vue
> +        if (err.data.data === 'tfa_required') {
돌고 있는 사이트에서 console 창에서 axios로 API 날려보면서 error handling 어떻게 되는지 확인할 수 있을 것 같네요

2021-07-03 12:14 UTC, dotoleeoak commented on frontend/src/pages/admin/views/problem/Problem.vue
>            if (this.routeName === 'create-contest-problem' || this.routeName === 'edit-contest-problem') {
그냥 개인적인 의견입니다

2021-07-04 01:17 UTC, dotoleeoak requested changes

2021-07-04 01:17 UTC, dotoleeoak commented on frontend/src/pages/admin/views/general/Conf.vue
> +      const resWeb = await api.getWebsiteConfig()
여기는 동시에 api 호출해서 parallel하게 받아오는 게 좋겠네요
```js
const [resSMTP, resWeb] = await Promise.all([api.getSMTPConfig(), api.getWebsiteConfig()])

2021-07-04 01:17 UTC, dotoleeoak commented on frontend/src/pages/oj/views/problem/Problem.vue
> +          if (err.data.data.startsWith('Captcha is required')) {
확인 필요

2021-07-04 01:59 UTC, Anzanda commented on frontend/src/pages/oj/views/user/ProfileSetting.vue
> +        if (err.data.data === 'tfa_required') {
아하 axios에서 resolve나 reject나 똑같은 res객체인 줄 알았는데 아닌가보네요... 찾아보고 수정하겠습니다!

2021-07-04 02:11 UTC, Anzanda commented on frontend/src/pages/oj/views/user/ProfileSetting.vue
> +        if (err.data.data === 'tfa_required') {
![F64363A9-8401-4EAB-A2F8-A0E568C7AF6D](https://user-images.githubusercontent.com/79851762/124370956-bf354f80-dcb7-11eb-814d-0967a0d5c100.png)
원래코드인데 reject일 때 res로 받고 res.data.data로 접근했네요. 원래코드도 잘못됐던 거 같기도하고ㅋㅎㅋ res.response.data로 접근하는 게 맞겠군요

2021-07-04 02:16 UTC, Anzanda commented on frontend/src/pages/oj/views/user/ProfileSetting.vue
> +        if (err.data.data === 'tfa_required') {
![9F8B9EF7-C6C1-4868-B3DE-1638E0F0D542](https://user-images.githubusercontent.com/79851762/124371021-be50ed80-dcb8-11eb-8220-c9e14827f5a1.png)
어! 근데 api.js의 ajax함수를 보면 axios통신 오류일 때는 err객체를 받는 건 분명한데(axios가 err객체를 response로 줌), 통신이 성공했을 때도 res.data.error에 따라 정상적인 res가 reject로 반환될 수도 있네요. 보면 이 코드는 후자일 때 상황만 신경써준 거 같아요. 백엔드에서 res.data.error는 어떤 건가요? 양쪽 경우를 모두 신경써야할 지 궁금하네요

2021-07-04 02:45 UTC, dotoleeoak commented on frontend/src/pages/oj/views/user/ProfileSetting.vue
> +        if (err.data.data === 'tfa_required') {
일단 전자의 상황은 무시해도 됩니다. 전자의 상황을 처리하려면 모든 API를 호출할 때마다 error handling을 해줘야된다는 건데, 그건 당연히 매우 번거로운 일이겠죠. 그래서 `ajax()` 함수에서 server error가 발생했을 때 error handling을 해주는거고, 다른 코드에서 `ajax()`로 API를 호출할 때에는 server error에 대한 handling은 고려하지 않아도 되는거죠.

2021-07-04 02:48 UTC, dotoleeoak commented on frontend/src/pages/oj/views/user/ProfileSetting.vue
> +        if (err.data.data === 'tfa_required') {
```python
class JSONResponse(object):
    content_type = ContentType.json_response

    @classmethod
    def response(cls, data):
        resp = HttpResponse(json.dumps(data, indent=4), content_type=cls.content_type)
        resp.data = data
        return resp
```

```python
class APIView(View):
    response_class = JSONResponse
    ...
    def response(self, data):
        return self.response_class.response(data)

    def success(self, data=None):
        return self.response({"error": None, "data": data})

    def error(self, msg="error", err="error"):
        return self.response({"error": err, "data": msg})
```

대략 구현이 이런 식으로 되어있는데, 각 API에서는 `success()`나 `error()`을 호출하여 응답합니다.
로그인 API를 예로 들면 아래와 같습니다.

```python
class UserLoginAPI(APIView):
    @validate_serializer(UserLoginSerializer)
    def post(self, request):
        data = request.data
        user = auth.authenticate(username=data["username"], password=data["password"])
        # None is returned if username or password is wrong
        if not user:
            return self.error("Invalid username or password")
        if user.is_disabled:
            return self.error("Your account has been disabled")
        if not user.has_email_auth:
            return self.error("Your need to authenticate your email")
        auth.login(request, user)
        return self.success("Succeeded")
```

즉, ID나 비밀번호를 잘못 입력한 경우에는 통신이 제대로 이뤄졌다는 가정 하에 아래와 같이 출력되겠죠.

```js
> console.log(res.data)
{ err: "error", data: "Invalid username or password" }
```

2021-07-04 02:50 UTC, dotoleeoak commented on frontend/src/pages/oj/views/user/ProfileSetting.vue
> +        if (err.data.data === 'tfa_required') {
일단 내용은 이런데, 언급했던 stackoverflow 내용 보니까 저 error handling이 제대로 될지 의문이어서 직접 브라우저에서 console창에 입력해보면서 error hanling이 제대로 되는지 확인해달라는 말이었습니다.

근데 어차피 이 부분은 #133 에서 지워질거라 굳이 고치진 않아도 될 것 같습니다.

2021-07-04 06:35 UTC, dotoleeoak commented
`.then` 검색해보면 아직 `async-await` 적용이 안된 코드들이 좀 있는데 확인 부탁드립니다~

2021-07-07 05:54 UTC, dotoleeoak commented
merge하는 커밋은 지우고 master에 rebase 해주세요

2021-07-07 05:58 UTC, dotoleeoak commented
interactive rebase를 사용하면 됩니다.
https://wormwlrm.github.io/2020/09/03/Git-rebase-with-interactive-option.html

```sh
git switch dev/async
git rebase -i HEAD~2

# 7beae46 Merge~
# pick에서 drop으로 바꾸기

git pull origin master
git rebase master

2021-07-07 14:42 UTC, Jeongcc commented
@Anzanda 윤성아 수정사항할 부분 커밋 올려줘 !

2021-07-08 16:18 UTC, minseo999 commented
<img width="441" alt="api" src="https://user-images.githubusercontent.com/76725982/124956482-007c8500-e053-11eb-9518-6abd3f00d450.PNG">

admin/api.js, oj/api.js 파일에 남은 promise .then을 async/await 으로 바꾸는 중에
get을 제외한 나머지 요청시 문제가 발생하고 있습니다. (로그인시 id, pw가 틀려도 로그인 성공 alert이 뜨거나 problem 삭제가 안되는 문제 등)

이부분의 async/await 로직을 어떻게 고쳐야할지 도움을 주실 수 있을까용
@dotoleeoak

2021-07-08 16:20 UTC, minseo999 commented
<img width="545" alt="캡처" src="https://user-images.githubusercontent.com/76725982/124957242-d5466580-e053-11eb-9660-d9881c581209.PNG">

2021-07-09 17:49 UTC, minseo999 commented
api.js 해결하고 커밋했습니다!

2021-07-10 06:28 UTC, dotoleeoak requested changes
![image](https://user-images.githubusercontent.com/19747913/125154127-6ec86100-e193-11eb-8d41-0dd5cdb528d8.png)
아직 조금 남아있는 부분도 같이 고쳐주세요~

2021-07-10 06:28 UTC, dotoleeoak commented on frontend/src/pages/admin/views/problem/AddPublicProblem.vue
> +        this.loading = false
이렇게 되면 `api.getProblemList()`에서 에러 생기면 `this.loading = false`가 적용될 수 없으니까, 이 부분은 `finally` 구문에 넣어야겠죠

2021-07-10 06:28 UTC, dotoleeoak commented on frontend/src/pages/admin/views/problem/AddPublicProblem.vue
> +      } catch (res) {
`res` => `err`

2021-07-10 06:52 UTC, minseo999 commented on frontend/src/pages/admin/api.js
> +    console.log(err)
try 구문 내부의  `if (res.data.error !== null)` 에서 에러가 잡혔을 때 기존 promise 를 사용할때는 reject()를 호출하여 api 함수를 호출하는 쪽에 에러를 날려줬는데, 코드를 변경하면서 `throw err` 로 에러를 날려주는 방식을 사용하려고 합니다
그런데 이때 catch 구문 내에서 `throw err` 만 해주게되면 eslint 에서 걸려서 console 코드를 추가해주었어요

2021-07-10 06:54 UTC, minseo999 commented on frontend/src/pages/admin/api.js
> +      // Vue.prototype.$error(res.data.data)
https://github.com/skku-npc/skku-coding-platform/issues/157
157번 이슈 관련해서 기존 element ui 메세지 박스를 사용하는 곳에서 에러가 발생하여 현재 주석처리 했습니다
해당 이슈 해결하면 이부분의 코드도 변경해야할 것 같아요!

https://element.eleme.io/#/en-US/component/message-box#messagebox

2021-07-10 06:57 UTC, dotoleeoak commented on frontend/src/pages/admin/api.js
> +    console.log(err)
음 `console` 추가하면 eslint에서 막는걸로 아는데 이상하네요

2021-07-10 07:02 UTC, dotoleeoak commented on frontend/src/pages/admin/api.js
> +    console.log(err)
https://eslint.org/docs/rules/no-useless-catch
eslint에서 걸린다는게 이 부분 같은데 `console` 빼면 코드가 아래처럼 돼서 그런가봐요
기껏 try-catch로 잡은 에러를 바로 throw해서 그런거겠죠?

```js
catch (err) {
  // Vue.prototype.$error(err.data.data)
  throw err
}

2021-07-10 07:04 UTC, dotoleeoak commented on frontend/src/pages/admin/api.js
> +    console.log(err)
그러려면 저 `Vue.prototype.$error` 주석이 해제되어야하고, 그러면 #157 먼저 해결이 되어야겠네요... 일단 보류하고 #157 먼저 해결해놓을게요

2021-07-10 07:06 UTC, minseo999 commented on frontend/src/pages/admin/api.js
> +    console.log(err)
맞아요! 저 catch에서 return err를 해주면 api함수 호출하는 쪽에서 반환값을 에러객체로 인식을 못하는 것 같아서 throw err를 해줬어요

2021-07-10 07:11 UTC, dotoleeoak commented on frontend/src/pages/admin/api.js
> +    console.log(err)
https://stackoverflow.com/questions/33445415/javascript-promises-reject-vs-throw
찾아보니까 async 함수 내부에서는 `throw` 대신 `reject`를 써야하는 것 같아요
확인 부탁드려요~

2021-07-10 14:41 UTC, dotoleeoak commented
alert 창 관련해서 해결했으니까 마저 정리해주세요~

2021-07-15 14:57 UTC, dotoleeoak requested changes

2021-07-15 14:57 UTC, dotoleeoak commented on frontend/src/pages/admin/views/general/Conf.vue
> +            })
이 promise 객체 반환하는 부분 async로 줄일 수 있을거 같기도 한데, 좀 고민해봐야될듯.
딱히 답 안보이면 그냥 넘어가도 됩니다

2021-07-15 14:57 UTC, dotoleeoak commented on frontend/src/pages/admin/views/general/Conf.vue
> +        await api.editWebsiteConfig(this.websiteConfig)
try-catch 안써도 되겠네요
```js
await api.editWebsiteConfig(this.websiteConfig).catch(() => {})

2021-07-15 14:57 UTC, dotoleeoak commented on frontend/src/pages/admin/views/problem/AddPublicProblem.vue
> +      } catch (res) {
`res` => `err`

2021-07-15 14:57 UTC, dotoleeoak commented on frontend/src/store/modules/contest.js
> +      return Promise.reject(res)
`reject` => `resolve`

2021-07-15 14:57 UTC, dotoleeoak commented on frontend/src/store/modules/contest.js
> +      return Promise.reject(err)
곳곳에 `Promise.reject()` 쓴 곳이 있는데, 썩 정상적인 방법은 아닌 것 같습니다.
async 함수에서는 그냥 `throw new Error(err)` 로 Error 객체를 반환하면 됩니다.
(그말인 즉슨 여기선 try-catch를 사용할 필요가 없겠죠. `catch` 구문의 무의미하니까요.)
아래 링크에 간단한 설명이 있습니다.
https://stackoverflow.com/questions/42453683/how-to-reject-in-async-await-syntax

2021-07-15 14:57 UTC, dotoleeoak commented on frontend/src/store/modules/contest.js
> +      return Promise.reject(err)
여긴 아래처럼 쓸 수 있겠죠
```js
async getContestAccess ({ commit, rootState }) {
  const res = await api.getContestAccess(...)
  commit(...)
  return res
}

2021-07-15 14:57 UTC, dotoleeoak commented on frontend/src/utils/utils.js
> +  }
여기도 try-catch가 필요없겠죠?

2021-07-15 14:57 UTC, dotoleeoak commented on frontend/src/utils/utils.js
> +    return Promise.reject(err)
마찬가지~

2021-07-15 14:57 UTC, dotoleeoak commented on frontend/src/pages/admin/api.js
> +  }
`frontend/src/store/modules/contest.js`에 써둔 커멘트 참고해서 고치면 되겠습니다.
(`oj/api.js`도 같이 고치는거 깜빡하지 말기)

2021-07-15 14:58 UTC, dotoleeoak commented
자꾸 고칠게 생기네... ㅎㅎ

2021-07-15 15:01 UTC, dotoleeoak commented on frontend/src/store/modules/contest.js
> +      return Promise.reject(err)
> 찾아보니까 async 함수 내부에서는 throw 대신 reject를 써야하는 것 같아요
확인 부탁드려요~

지금 보니까 전에 올렸던 커멘트랑 앞뒤가 안맞는데... 찾아보니까 `throw` 쓰는게 맞는거 같네요
번거롭게 해서 죄송합니다...ㅎㅎ

2021-07-17 10:12 UTC, minseo999 commented
브랜치 마스터로 rebase 후 commit 했습니다🙏 @dotoleeoak

2021-07-17 11:09 UTC, dotoleeoak requested changes
조금만 더 확인해주세요~

2021-07-17 11:09 UTC, dotoleeoak commented on frontend/src/utils/utils.js
> +    }
```js
const fr = new window.FileReader()
Vue.prototype.$error(res.data.error | 'Invalid file format')
```

2021-07-17 11:09 UTC, dotoleeoak commented on frontend/src/utils/utils.js
> +        Vue.prototype.$error('Invalid file format')
```js
const data = JSON.parse(...)
Vue.prototype.$error(data.error ? data.data : 'Invalid file format')
```

2021-07-17 11:09 UTC, dotoleeoak commented on frontend/src/utils/utils.js
> +  return res
`res` 반환하는게 맞나요? 원본 코드 보면 안해도 될거 같습니다

2021-07-17 11:09 UTC, dotoleeoak commented on frontend/src/utils/utils.js
> +  return Promise.resolve(languages)
```js
return languages
```

2021-07-17 11:09 UTC, dotoleeoak commented on frontend/src/utils/utils.js
> +    return Promise.resolve(storageLanguages)
```js
return storageLanguages
```

2021-07-17 11:59 UTC, minseo999 commented on frontend/src/utils/utils.js
> +        Vue.prototype.$error('Invalid file format')
https://sweetalert2.github.io/
![image](https://user-images.githubusercontent.com/76725982/126036089-92a630aa-1207-4119-9389-60f585ccf5e1.png)
저부분 elementui에서 부트스트랩 뷰 simple alert 사용하는걸로 대체했는데, simple alert는 inputValidaor 값으로 Promise객체를 사용해서 기존대로 가는게 맞지 않을까요??

2021-07-17 12:18 UTC, dotoleeoak commented on frontend/src/utils/utils.js
> +        Vue.prototype.$error('Invalid file format')
async 함수의 return 값이 Promise 객체입니다 (그래서 문서에도 async 함수를 쓸 수 있다고 써있네요)

2021-07-17 12:21 UTC, dotoleeoak commented on frontend/src/utils/utils.js
> +        Vue.prototype.$error('Invalid file format')
추가 설명) 아래 두 함수는 동일합니다
```js
async function foo() {
    return 1
}
```

```js
function foo() {
    return Promise.resolve(1)
}
```

2021-07-17 13:21 UTC, minseo999 commented
커밋 수정했습니다 ㅎㅎ 진짜 마지막 ,,,?ㅎㅎ  @dotoleeoak

2021-07-17 13:46 UTC, minseo999 commented
#173 수정사항이 한줄이라서 이곳에 커밋 올렸습니다

2021-07-17 15:17 UTC, minseo999 commented on frontend/src/utils/utils.js
> +        Vue.prototype.$error('Invalid file format')
이 코멘트를 늦게 확인했네요😥 오전중에 확인하고 커밋 수정하겠습니다,,!

2021-07-17 16:33 UTC, minseo999 commented
늦게 확인한 코멘트까지 반영해서 커밋 수정 완료했습니다 😊

2021-07-17 23:39 UTC, dotoleeoak commented
> #173 수정사항이 한줄이라서 이곳에 커밋 올렸습니다

Close #173

2021-07-19 01:19 UTC, dotoleeoak requested changes
수고하셨습니다
commit 정리해주시면 approve할게요 (squash 부탁드립니다)

2021-07-21 09:29 UTC, dotoleeoak approved these changes
Rebase and merge 부탁드립니다~

2021-07-21 10:38 UTC, merged