ElementUI -> BootstrapVue 수정
skku-npc/skku-coding-platform pull request #138
Opened 2021-07-01 15:14 UTC by y-jiu

Login.vue
Conf.vue
Dashboard.vue
ElementUI -> BootstrapVue로 수정

2021-07-01 15:30 UTC, y-jiu commented
Login.vue 에서 로그인 안되는 문제 발생
금요일에 @click.native.prevent 관련 수정 방향 찾아볼 예정

2021-07-02 11:44 UTC, cranemont requested changes
추가적으로 기존처럼 필수 입력란은 *를 사용해서 표시해주는 것이 좋을 듯 합니다. v-slot을 사용하면 표시 가능합니다. Web Config부분을 그렇게 바꿔두었으니 참고해서 변경해주세요!

2021-07-02 11:44 UTC, cranemont commented on frontend/src/pages/admin/views/general/Conf.vue
>      <Panel :title="$t('m.SMTP_Config')">
i18n기능은 사용하지 않을 예정입니다. $t(~~)를 사용한 title속성들은 페이지에 표시되는 텍스트로 바꿔주세요!

2021-07-02 11:44 UTC, cranemont commented on frontend/src/pages/admin/views/general/Conf.vue
> +                required>
required속성은 현재 구조에서는 의미가 없어서 지우셔도 됩니다.

2021-07-02 11:44 UTC, cranemont commented on frontend/src/pages/admin/views/general/Conf.vue
> +                    type="textarea"
b-form-textarea를 사용하면 기존처럼 textarea 형식의 input을 사용 가능합니다. 
https://bootstrap-vue.org/docs/components/form-textarea 여기를 참고해주세요!

2021-07-02 11:44 UTC, cranemont commented on frontend/src/pages/admin/views/general/Dashboard.vue
>              {{ $t('m.Last_Login') }}
마찬가지로 i18n을 사용한 부분들을 변경해주시면 됩니다.

2021-07-02 11:44 UTC, cranemont commented on frontend/src/pages/admin/views/general/Login.vue
>        {{ $t('m.Welcome_to_Login') }}
~~~~

2021-07-02 14:05 UTC, dotoleeoak commented on frontend/src/pages/admin/views/general/Dashboard.vue
>              {{ $t('m.Last_Login') }}
i18n은 나중에 한번에 변경할거라 지금 안해도 됩니다
따로 i18n 정리하는 PR 만들어서 하는게 나을 것 같네요

2021-07-02 14:18 UTC, cranemont commented on frontend/src/pages/admin/views/general/Dashboard.vue
>              {{ $t('m.Last_Login') }}
확인했습니다. 그럼 그렇게 진행할게요!

2021-07-02 14:21 UTC, y-jiu commented on frontend/src/pages/admin/views/general/Dashboard.vue
>              {{ $t('m.Last_Login') }}
헉 이미 i18n 이번 파일에 반영했는데 pr 올려도 될까요...?? 아님 원상복구 할까요?

2021-07-02 14:22 UTC, cranemont commented on frontend/src/pages/admin/views/general/Dashboard.vue
>              {{ $t('m.Last_Login') }}
어차피 나중에 수정해야 되는 부분이니 바꾸신건 그대로 PR 올려주셔도 괜찮을 것 같습니다

2021-07-02 14:23 UTC, y-jiu commented on frontend/src/pages/admin/views/general/Dashboard.vue
>              {{ $t('m.Last_Login') }}
넵 알겠습니다 !

2021-07-03 15:54 UTC, cranemont approved these changes

2021-07-03 15:58 UTC, merged

2021-07-04 04:28 UTC, Jeongcc commented
PR merge 한 뒤에는 자기 branch 삭제해주세요 ! @y-jiu