postgresql deadlock issue 관련 수정
skku-npc/skku-coding-platform pull request #156
Opened 2021-07-09 11:16 UTC by ghdwlsrl3229

데드락 이슈는 대량의 submission이 발생할 때, 아래 코드에 의해서 발생합니다. 

```jsx
servers = JudgeServer.objects.select_for_update().filter(is_disabled=False).order_by("task_number")
```

select for update 쿼리의 데드락을 피하는 방법은 select된 row들을 order_by로 특정 순서로 정렬한 후에 lockrows을 걸도록 하는 것입니다. 하지만 기존의 정렬 기준인 task_number는 unique하지 않고, 상황에 따라 값이 바뀔 수 있어서 데드락을 회피하기에는 적절하지 않은 정렬 기준이라고 생각했습니다. 따라서 primary key인 id를 정렬 기준으로 사용해서 postgresql에서 데드락을 피하도록 하고, 값을 받아온 이후 task_number로 재정렬하도록 수정했습니다.

간단하게 테스트해봤을 때 데드락이 발생하지는 않았지만, 데드락 오류 자체가 매우 레어하게 발생하기 때문에 해결된 것인지 우연히 발생하지 않은 것인지 판별이 어렵습니다.

2021-07-10 06:55 UTC, 22222bh approved these changes
월요일에 마지막으로 테스트 해보고 머지해주세요 수고하셨습니다.

2021-07-10 07:00 UTC, dotoleeoak requested changes
좀만 더 확인해볼게요... 기다려주세요ㅠ

2021-07-10 08:09 UTC, dotoleeoak commented
이해가 안되는 부분이 몇 있습니다.

1. 아마 테스트 환경에서는 `JudgeServer`가 하나로 유일했을텐데, deadlock의 원인이 정렬 기준이 아닐 가능성도 있지 않나요?
2. 만약 정렬 기준이 원인이라해도, 채점을 `task_number`가 적은 `JudgeServer`에 할당하는 것이 좋기 때문에 정렬 기준 자체를 바꾸는 것은 바람직하지 못한 것 같습니다. 로직 자체를 수정해야할 것 같습니다.

2021-07-11 04:02 UTC, ghdwlsrl3229 commented
1. postgresql에서 judge_server 테이블을 살펴보면 아래와 같습니다. 왜 judge_server가 3개가 등록되어 있는가는 차치하고, judge_server가 3개가 등록되어 있기 때문에 정렬 순서로 인해서 데드락이 발생할 가능성은 있습니다. judge_server를 하나만 남기고 나머지는 삭제해도 데드락은 해결되겠지만, 쿼리를 수정하는 쪽이 더 근본적인 해결책이라고 생각합니다.

```jsx
onlinejudge=# select * from judge_server;
 id |   hostname   |     ip     | judger_version | cpu_core | memory_usage | cpu_usage |        last_heartbeat         |          create_time          | task_number |       service_url        | is_disabled
----+--------------+------------+----------------+----------+--------------+-----------+-------------------------------+-------------------------------+-------------+--------------------------+-------------
  1 | 0066675e4737 | 172.20.0.3 | 2.1.1          |        4 |         41.6 |         0 | 2021-07-09 09:10:49.015699+00 | 2021-07-09 08:47:48.098431+00 |           0 | http://judge-server:8080 | f
  2 | 5d3f4abbba6e | 172.20.0.4 | 2.1.1          |        4 |         43.3 |       100 | 2021-07-09 09:25:13.230231+00 | 2021-07-09 09:11:41.166893+00 |           0 | http://judge-server:8080 | f
  3 | 9918fe66981a | 172.18.0.5 | 2.1.1          |        4 |         35.3 |       100 | 2021-07-11 03:44:02.479551+00 | 2021-07-09 09:34:22.512622+00 |           0 | http://judge-server:8080 | f
(3 rows)
```

2. select for update 쿼리를 날릴 때에는 id 순서대로 정렬을 요청하지만, 쿼리의 결과를 다시 task_number로 재정렬해주도록 수정했기 때문에 task_number가 작은 서버에 배정하는 로직은 달라지지 않았습니다.

2021-07-13 06:01 UTC, dotoleeoak commented
@ghdwlsrl3229 그러면 정렬이 필요없는건가요? 아래처럼 고치는건 어떤가요?
```python
servers = JudgeServer.objects.select_for_update().filter(is_disabled=False)

2021-07-13 06:27 UTC, ghdwlsrl3229 commented
@dotoleeoak select_for_update를 할 때 데드락을 피하기 위해서 정렬이 필요합니다. 이 때의 기준을 unique한 값인 id로 잡아줬습니다.

2021-07-14 02:18 UTC, dotoleeoak approved these changes
넵 알겠습니다

2021-07-14 02:19 UTC, dotoleeoak commented
"Rebase and merge" 부탁드립니다

2021-07-14 10:05 UTC, merged