Add locust.py for load test
skku-npc/skku-coding-platform pull request #168
Opened 2021-07-11 14:03 UTC by joft-ware

- locust.py 추가(load test)
- backend/deploy/requirements.txt에 locust 1.6.0 추가

2021-07-12 05:12 UTC, 22222bh commented
@dotoleeoak  docker cloud 테스트는 처음 보는데 이번에 도커허브 관련 수정하면서 새로 생긴 건가요?? details 눌러도 404가 나오네요

2021-07-12 09:50 UTC, dotoleeoak commented
@22222bh 원래 있던건데 접근 허용된 사람(최대 3명인데 이미 꽉 참...)만 링크 들어갈 수 있어서 그럴거예요

2021-07-13 05:18 UTC, dotoleeoak requested changes
root directory에 locust.py를 두는 것은 바람직하지 않은 것 같습니다.
backend에서만 쓰이는 파일이니 backend 폴더에 두고, 하위 폴더를 만들지는 직접 선택해도 되겠습니다.
아마 backend 폴더 아래로 옮기면 flake8 검사에 걸릴텐데, style 수정도 해주세요.

2021-07-28 15:12 UTC, joft-ware commented
기간이 좀 오래 지난 관계로 따로 PR 올렸습니다! 
#192

2021-07-28 15:12 UTC, closed without merging