User/Jooyoung
skku-npc/skku-coding-platform pull request #17
Opened 2021-01-17 00:30 UTC by illuminoplanet

2021-01-17 02:19 UTC, dotoleeoak commented
@illuminoplanet `master` -> `user/Jooyoung` 먼저 merge 해줘
`master` 변경사항 반영 안된듯

2021-01-17 08:33 UTC, Jeongcc commented
![image](https://user-images.githubusercontent.com/46365350/104835439-0d14f180-58ea-11eb-9605-5dd6154c4f3e.png)
Empty file.이라고 뜨는 이유 아시나요?

2021-01-17 12:13 UTC, illuminoplanet commented
내일 함
좀 귀찮네

2021-01-18 01:40 UTC, dotoleeoak requested changes
- comment 확인 후 해결할 것
- diff 없이 staging된 파일들 원인 찾기

2021-01-18 01:40 UTC, dotoleeoak commented on JudgeServer/.gitignore
> +>>>>>>> de292f7fd8c143ddb02dc1a623707a45f8f91fdc:JudgeServer/.gitignore
Merge conflict 정리할 것

2021-01-18 01:40 UTC, dotoleeoak commented on OnlineJudgeFE/src/store/modules/contest.js
> +let padZero = (n) => (n < 10 ? '0' + n : n)
Use more desirable way
(Don't declare function here)

2021-01-18 01:42 UTC, dotoleeoak commented on OnlineJudgeFE/src/store/modules/contest.js
> +let padZero = (n) => (n < 10 ? '0' + n : n)
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/String/padStart

2021-01-26 01:06 UTC, closed without merging