fix frontend issues
skku-npc/skku-coding-platform pull request #176
Opened 2021-07-21 11:57 UTC by SOLBI1028

- contest problem이 많아질 시 sidebar 버튼이 잘리는 문제해결 #164 
- contest problem list, problem sidebar 에 problem list가 display id 순서대로 정렬이 되지 않는 문제해결 #175
- edit SCSS

2021-07-21 12:08 UTC, DailyPS commented
edit SCSS 관련

현재 다음 파일들에서 scss로 변경되지 않았습니다.

/admin/components/btn

- infoCard.vue

/admin/components/btn

- Cancel.vue
- Save.vue

2021-07-23 14:15 UTC, jimin9038 requested changes
- 사이드바에 하얀색이 있으면 별로 안 예쁜 것 같아 코멘트 드린대로 사이드바 수정해주시고,
- infoCard.vue 34번째 줄에 name이 InforCard로 되어있는데 단순 typo인 것 같습니다. 커밋하는 김에 InfoCard 로 같이 고쳐주세요~

2021-07-23 14:21 UTC, SOLBI1028 commented on frontend/src/pages/oj/views/problem/ProblemSidebar.vue
> -    height: 100%;
넵~!

2021-07-23 16:49 UTC, jimin9038 approved these changes
Great!

2021-07-24 06:05 UTC, merged