유저 정보 입력 수정
skku-npc/skku-coding-platform pull request #18
Opened 2021-01-17 02:33 UTC by dotoleeoak

## 입력란 수정
__username__ : 학번 입력 강제
__email__ : @g.skku.edu, @skku.edu 도메인 강제
__major__ : 전공 입력 칸 추가

2021-01-17 02:56 UTC, dotoleeoak commented
## TODO
- major 항목 백엔드 적용  __#backend__
  - `UserProfile` => `User` table
  - major 관련 view 등도 수정 필요
- 가입 시 major field 추가 __#frontend__

<img src="https://user-images.githubusercontent.com/19747913/104829810-d70c4900-58ba-11eb-8990-e40f573d4b4d.png" width=400>

2021-01-17 08:37 UTC, Jeongcc approved these changes
확인했습니다

2021-01-26 14:12 UTC, Jeongcc requested changes
좋아요!

2021-01-26 14:12 UTC, Jeongcc commented on OnlineJudgeFE/src/pages/oj/views/user/Register.vue
> +          ]
여기는 일부러 이 정도 과만 입력한거죠? 학과 사무실에 전화해서 학과리스트 받아볼게요

2021-01-26 14:12 UTC, Jeongcc commented on docker-compose.yml
> -  judge-server:
judge-server로 다시 바꾸기!

2021-01-26 14:12 UTC, Jeongcc commented on docker-compose.yml
>      image: skkunpc/judger
도커에 올라간 이미지도 judge-server로 맞추는게 좋겠습니다

2021-01-26 14:12 UTC, Jeongcc commented on docker-compose.yml
> +version: "3.8"
여기도 우선 version: "3"

2021-01-30 11:24 UTC, Jeongcc commented on docker-compose.yml
> +      - judger
judge-server 로 다시 바꿔주세요 :)

2021-01-30 11:25 UTC, Jeongcc requested changes
docker-compose.yml 파일에 마이너한 부분만 바꾸면 됩니다!

2021-01-31 16:30 UTC, dotoleeoak commented
@Jeongcc 확인 부탁드릴게요

2021-02-01 12:35 UTC, Jeongcc approved these changes

2021-02-01 12:38 UTC, merged