Add katex preview in create problem page
skku-npc/skku-coding-platform pull request #201
Opened 2021-08-02 16:22 UTC by y-jiu

Admin에서 Problem Create/Edit 할 때,
Description, Hint 부분에  Katex 적용 결과를 확인 가능한 미리보기 창 추가

2021-08-04 02:14 UTC, jimin9038 approved these changes
LGTM!

2021-08-06 05:42 UTC, dotoleeoak requested changes

2021-08-06 05:42 UTC, dotoleeoak commented on frontend/src/pages/admin/components/KatexEditor.vue
> +    For example, \( \pm\sqrt{a^2 + b^2}  \)
영어로 수정해주세요~
(예전에 교수님께 코딩 플랫폼 전반은 영어로 구성해달라는 요청을 받았습니다)

2021-08-06 05:42 UTC, dotoleeoak commented on frontend/package.json
> +    "vue-katex": "^0.5.0",
기존의 katex 패키지 외에 vue-katex 패키지는 왜 추가로 설치했나요?

2021-08-06 05:51 UTC, dotoleeoak commented on frontend/src/pages/admin/components/KatexEditor.vue
> +    For example, \( \pm\sqrt{a^2 + b^2}  \)
에디터에서 LaTex 적용하기 위한 delimiter가 아래처럼 `$$ ... $$`, `\[ ... \]` 도 있으니까 설명 추가 부탁드립니다.
(`$`는 왜인지 모르겠지만 적용이 안 되는 거 같네요)
```js
// katex.js
const defaultOptions = {
  errorCallback: _,
  throwOnError: false,
  delimiters: [
    { left: '$', right: '$', display: false },
    { left: '$$', right: '$$', display: true },
    { left: '\\[', right: '\\]', display: true },
    { left: '\\(', right: '\\)', display: false }
  ]
}
```

![image](https://user-images.githubusercontent.com/19747913/128462421-28dd7dd0-fd51-4e02-9082-27998d932ce7.png)
![image](https://user-images.githubusercontent.com/19747913/128462443-1ef91a81-9b52-4f34-8192-acd616b58d5b.png)

2021-08-06 08:19 UTC, jimin9038 commented on frontend/package.json
> +    "vue-katex": "^0.5.0",
일반 katex 패키지는 vue에서 사용하려면 복잡하여 katex 공식 홈페이지에서 추천하는 vue-katex를 이용하여 렌더링 하였습니다.
![image](https://user-images.githubusercontent.com/73051219/128480042-ad38e820-653f-455f-a609-29e1d63fd42c.png)

2021-08-06 09:54 UTC, dotoleeoak commented on frontend/package.json
> +    "vue-katex": "^0.5.0",
그러면 기존 katex를 지우고 사용하는게 좋지 않을까요?

2021-08-06 10:08 UTC, jimin9038 commented on frontend/package.json
> +    "vue-katex": "^0.5.0",
Vue-katex는 katex를 편하게 사용할 수 있게 하는 익스텐션이라 katex 패키지가 따로 필요합니다.

2021-08-06 10:18 UTC, dotoleeoak commented on frontend/package.json
> +    "vue-katex": "^0.5.0",
그건 yarn이 알아서 패키지 의존성을 해결하면서 yarn.lock에 추가해주겠죠? package.json에 직접 추가할 필요는 없겠죠

2021-08-06 11:39 UTC, jimin9038 commented on frontend/package.json
> +    "vue-katex": "^0.5.0",
흠.. 해봤는데 vue-katex만 package.json에 추가하면 yarn install했을 때 yarn.lock에 katex가 추가가 안되는 것 같은데요. 확인해봐주실 수 있을까요?

2021-08-06 11:39 UTC, jimin9038 commented on frontend/package.json
> +    "vue-katex": "^0.5.0",
+ vue-katex 리포입니다
![image](https://user-images.githubusercontent.com/73051219/128505138-6560edf8-cad4-4d90-9516-93863f647c50.png)

2021-08-07 03:43 UTC, dotoleeoak commented on frontend/package.json
> +    "vue-katex": "^0.5.0",
그러면 katex는 추가로 설치한다고 치고, 지금은 plugin 폴더에 katex component를 정의해서 쓰고 있는데 그거를 지우거나 해야되지 않을까요?

2021-08-13 17:48 UTC, jimin9038 commented on frontend/package.json
> +    "vue-katex": "^0.5.0",
katex plugin 지워서 katexEditor에도 적용해놓았고, 충돌난것들 처리하고 master에 rebase해놓았습니다.

2021-08-13 17:49 UTC, jimin9038 commented
추가로 admin/problem.vue에서 v-html 대신 v-dompurify-html을 사용하려고 했으나 어떤 이유에선지 katex가 적용이 되지 않네요. admin이니 보안상 문제가 있을 것 같진 않지만..

2021-08-14 15:00 UTC, dotoleeoak commented
> 추가로 프리뷰 보여줄때 v-html 대신 v-dompurify-html을 사용하려고 했으나 어떤 이유에선지 katex가 적용이 되지 않네요. admin이니 보안상 문제가 있을 것 같진 않지만..

@jimin9038 나는 v-dompurify-html로 고쳐도 되는거 같은데, 다시 확인해줄 수 있어?
![image](https://user-images.githubusercontent.com/19747913/129450447-58af2997-3220-460c-8e28-32a8a47699d4.png)
![image](https://user-images.githubusercontent.com/19747913/129450475-ad410aff-d49d-46a1-af2a-4087d3db8aec.png)

2021-08-15 06:43 UTC, jimin9038 commented
> > 추가로 프리뷰 보여줄때 v-html 대신 v-dompurify-html을 사용하려고 했으나 어떤 이유에선지 katex가 적용이 되지 않네요. admin이니 보안상 문제가 있을 것 같진 않지만..
> 
> @jimin9038 나는 v-dompurify-html로 고쳐도 되는거 같은데, 다시 확인해줄 수 있어?
> ![image](https://user-images.githubusercontent.com/19747913/129450447-58af2997-3220-460c-8e28-32a8a47699d4.png)
> ![image](https://user-images.githubusercontent.com/19747913/129450475-ad410aff-d49d-46a1-af2a-4087d3db8aec.png)

@dotoleeoak 나도 v-html 만 v-dompurify-html 로 바꿔서 테스트해봤는데 잘 안되는 것 같네. 뭐가 문제지
https://user-images.githubusercontent.com/73051219/129469633-86be3093-462f-4c8d-8f3b-521cd30b2665.mp4

2021-08-15 14:45 UTC, dotoleeoak commented
@jimin9038 좀 살펴보니까 katex랑은 관계 없는 거 같고(일반 텍스트도 사라지는 현상 똑같이 발생), modal 밖에서 `v-dompurify-html` 썼을 때는 잘 되는 거 보니까 bootstrap modal이랑 관련된거 같아

2021-08-15 14:45 UTC, dotoleeoak commented
@jimin9038 Bootstrap Vue 원본 코드에서 modal toggle할 때 어떻게 동작하는 지 살펴봐

2021-08-15 14:50 UTC, dotoleeoak commented
`v-b-modal` directive 코드
https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/directives/modal/modal.js

2021-08-17 06:06 UTC, dotoleeoak requested changes

2021-08-17 06:49 UTC, dotoleeoak commented
위에 `v-dompurify-html` 문제는 살펴봤어?

2021-08-17 06:54 UTC, jimin9038 commented
살펴봤는데 어디서 오류나는지 못 찾겠음..

2021-08-22 07:56 UTC, dotoleeoak commented
@jimin9038 `v-dompurify-html` 문제 해결했으니까 확인해봐

2021-08-22 07:59 UTC, dotoleeoak approved these changes

2021-08-25 08:39 UTC, jimin9038 commented
확인했습니다 rebase and merge 할게요~

2021-08-25 11:41 UTC, merged