문제별로 시간/메모리 제한 추가
skku-npc/skku-coding-platform pull request #227
Opened 2021-09-05 11:52 UTC by Anzanda

[백준](https://www.acmicpc.net/help/language)에서 언어별 시간/메모리제한의 가중치를 두는 것을 참고해서 적용했습니다.  #215

2021-09-05 11:53 UTC, dotoleeoak commented
#215 에서 언급한 기능은 admin이 문제 출제 시 직접 시간을 조절할 수 있는 기능 아닌가요?

2021-09-05 12:13 UTC, Anzanda commented
> #215 에서 언급한 기능은 admin이 문제 출제 시 직접 시간을 조절할 수 있는 기능 아닌가요?

처음에는 admin이 문제를 낼 때 , 문제마다 언어별로 시간을 다르게 설정해야겠다 생각했습니다. 하지만 이 방법은 언어별 시간/메모리제한에 대한 데이터를 가지고 있어야 하고 전달해줘야 되기 때문에 DB의 조작이 필요할 거 같습니다. 그래서 이렇게 하지 않고 공신력 있는? 백준의 방식을 채택해서 사용하고자 한 것입니다.

2021-09-05 17:00 UTC, cranemont commented on backend/judge/dispatcher.py
> +        problem.time_limit = problem.time_limit * 3 + 2
time limit설정은 ms를 기준으로 되어있습니다. 2 -> 2000으로 바꿔주세요!

2021-09-05 17:00 UTC, cranemont commented on backend/judge/dispatcher.py
> +        problem.time_limit = problem.time_limit * 2 + 1
1 -> 1000

2021-09-05 17:01 UTC, cranemont commented on backend/judge/dispatcher.py
> +        problem.time_limit = problem.time_limit + 2
2 -> 2000

2021-09-05 17:02 UTC, cranemont commented on backend/judge/dispatcher.py
> +
작은따옴표들 큰따옴표로 변경해주세요~

2021-09-06 07:09 UTC, cranemont requested changes

2021-09-06 07:31 UTC, dotoleeoak commented
그러면 제 생각에는 이렇게 하드코딩하는 것보다는 languages.py에 언어별로 lambda 함수를 추가하는 방식 등으로 구현하는게 좋을 거 같네요

2021-09-11 05:24 UTC, cranemont approved these changes

2021-09-11 05:29 UTC, cranemont commented
@Anzanda Rebase and merge 해주세요~

2021-09-11 05:32 UTC, dotoleeoak requested changes
좀 만 더 보고 approve할게요

2021-09-11 05:42 UTC, dotoleeoak requested changes
languages.py에서 `change_time`이랑 `change_memory` 변수를 따로 추가하는게 아니라, 위의 언어별 config (`languages`)에서 각 언어별로 직접 lambda 함수를 추가해달라는게 제 의도였어요. 예를 들어서 Python3은 아래처럼 되겠죠.

```python
{
    "config": _py3_lang_config,
    "name": "Python3",
    "description": "Python 3.6",
    "content_type": "text/x-python",
    "time_limit": lambda x: x * 3 + 2000,
    "memory_limit": lambda x: x * 2 + 32
},
```

그러면 dispatcher.py에서도 `import judge.langues`를 추가할 필요 없이, 구현이 간단해지겠죠.

```python
data = {
    "language_config": sub_config["config"],
    "max_cpu_time": sub_config["time_limit"](self.problem.time_limit),
    "max_memory": ...
}
```

2021-09-11 06:21 UTC, Anzanda commented
> languages.py에서 `change_time`이랑 `change_memory` 변수를 따로 추가하는게 아니라, 위의 언어별 config (`languages`)에서 각 언어별로 직접 lambda 함수를 추가해달라는게 제 의도였어요. 예를 들어서 Python3은 아래처럼 되겠죠.
> 
> 
> 
> ```python
> 
> {
> 
>     "config": _py3_lang_config,
> 
>     "name": "Python3",
> 
>     "description": "Python 3.6",
> 
>     "content_type": "text/x-python",
> 
>     "time_limit": lambda x: x * 3 + 2000,
> 
>     "memory_limit": lambda x: x * 2 + 32
> 
> },
> 
> ```
> 
> 
> 
> 그러면 dispatcher.py에서도 `import judge.langues`를 추가할 필요 없이, 구현이 간단해지겠죠.
> 
> 
> 
> ```python
> 
> data = {
> 
>     "language_config": sub_config["config"],
> 
>     "max_cpu_time": sub_config["time_limit"](self.problem.time_limit),
> 
>     "max_memory": ...
> 
> }
> 
> ```

오.. 감사합니다!ㅎㅎ

2021-10-31 10:34 UTC, dotoleeoak approved these changes

2021-10-31 14:21 UTC, merged