Add HSTS, CSP headers
skku-npc/skku-coding-platform pull request #228
Opened 2021-09-05 12:21 UTC by Anzanda

예전에 재민이형님이 올려주신 [보안테스트 결과](https://snyk.io/test/website-scanner/?test=210815_BiDcT2_9176c805959bebfff7f690f44a431a2b&utm_medium=referral&utm_source=webpagetest&utm_campaign=website-scanner)에서 부족한 헤더들을 추가해줬습니다.

- HSTS설정: [nginx공홈](https://www.nginx.com/blog/http-strict-transport-security-hsts-and-nginx/)을 참고하여 `nginx.config`에 추가하였습니다.  헤더와 함께 자동으로 HTTPS로 리다이렉트 되도록 설정해줬습니다.
- CSP설정: 이 [링크](https://content-security-policy.com/examples/nginx/)를 참고해서 CSP헤더 또한 추가하였습니다. 옵션으로 어떠한 URI는 허용한다 라고 정할 수 있는데, 아직 우리 프로젝트에 허용할 만한 사이트가 없는 거 같아 default로 설정해줬습니다.

2021-09-06 10:08 UTC, cranemont requested changes
FORCE_HTTPS관련 코드들도 같이 제거해주세요

2021-09-06 10:08 UTC, cranemont commented on backend/deploy/nginx/nginx.conf
> +    }
해당 서버 블록을 추가하지 않아도 됩니다. entrypoint설정을 보시면 아시겠지만 http_locations.conf라는 심볼릭 링크를 만들어서 사용합니다.
![entrypoint](https://user-images.githubusercontent.com/71835056/132198883-8b3137c1-d942-4390-9e3e-9ba7d01926a8.PNG)
또 서버의 80번 포트는 docker-compose파일에 나와있듯이 이미 coding-platform 컨테이너의 8000번 포트와 연결되어 있습니다. 해당 요청을 받는 서버 블록이 listen 8000~ 이 포함된 블록이구요. 
제 생각에는 https_redirect.conf파일의 내용을 기존 서버 블록에 포함시키는 것이 좋을 것 같습니다.

2021-09-06 10:13 UTC, dotoleeoak commented on backend/deploy/nginx/nginx.conf
> +    }
제가 하려던 말을 적어두셨네요 ㅎㅎ

2021-09-06 10:19 UTC, cranemont commented
CSP 헤더에 google-analytics는 추가해야 할 것 같습니다
![google](https://user-images.githubusercontent.com/71835056/132201697-a8401c9f-ce91-4557-bd60-cc46f50c2740.PNG)
혹시 또 추가해야 할 URL이 있는지 확인 부탁드려요

2021-09-24 08:55 UTC, cranemont submitted a review, later dismissed

2021-10-31 13:26 UTC, dotoleeoak requested changes

2021-10-31 13:26 UTC, dotoleeoak commented on backend/deploy/entrypoint.sh
>  ln -sf locations.conf https_locations.conf
라인 27 지우고 nginx.conf도 수정하는게 나을 것 같네요

2021-11-02 18:11 UTC, cranemont commented on backend/deploy/entrypoint.sh
>  ln -sf locations.conf https_locations.conf
@dotoleeoak 수정했습니다~~

2021-11-02 22:12 UTC, dotoleeoak approved these changes

2021-11-03 05:46 UTC, merged