Fix contest(2차 모의대회 issues
skku-npc/skku-coding-platform pull request #234
Opened 2021-09-10 05:22 UTC by jimin9038

모의대회에서 발생할 프론트엔드 이슈 해결
1. admin - problem.vue : Problem edit에서 불러온 테스트케이스가 50mb를 넘을 시 테스트케이스를 렌더링하거나 새로 업로드하지 않도록 변경 (학산)
2. clarification edit ← 경환
3. admin 대시보드 submission list ←경환
4. testcase 용량 관련 ←학산

2021-09-10 05:50 UTC, DailyPS commented
Today Submisson 관련 부분은 merge 후 dev 브랜치로 새로 작업하겠습니다. 하루 동안에 있던 제출을 확인하는 것보다, Problem별 제출을 확인하는 것이 적합하다고 생각합니다.

2021-09-10 06:28 UTC, jimin9038 commented
> Today Submisson 관련 부분은 merge 후 dev 브랜치로 새로 작업하겠습니다. 하루 동안에 있던 제출을 확인하는 것보다, Problem별 제출을 확인하는 것이 적합하다고 생각합니다.

(참고)Admin에서 각 problem 별로 submission을 볼 수 없는게 있을 법한데 없어서 만들 예정입니다.

2021-09-10 08:18 UTC, SOLBI1028 commented
![image](https://user-images.githubusercontent.com/75013515/132822585-0899cb30-6624-4ced-91a1-474b55aa8bd8.png)

reset 버튼 옆 badge 눌러서 제출 상태 확인하는 모달 띄웠을때 아직 코드가 깨져 보이네요 ㅜ (#194)

2021-09-10 08:24 UTC, DailyPS commented
> ![image](https://user-images.githubusercontent.com/75013515/132822585-0899cb30-6624-4ced-91a1-474b55aa8bd8.png)
> 
> reset 버튼 옆 badge 눌러서 제출 상태 확인하는 모달 띄웠을때 아직 코드가 깨져 보이네요 ㅜ (#194)

이건 깨진게 아니라 CSS 설정이 충돌 나서 소스 코드가 왼쪽으로 치우쳐져 안보이는 문제로 확인했습니다.
확인 당시에 Problem 부분 Refactoring을 한 뒤에 다시 확인하는 걸로 했었던 기억이 나네요

2021-09-15 07:09 UTC, dotoleeoak requested changes

2021-09-15 07:09 UTC, dotoleeoak commented on frontend/src/pages/admin/views/general/Announcement.vue
> +          this.contestAnnouncementList.find(item => {
중복되는 부분은 지우고 이 부분만 삼항 연산자로 구현하는 게 좋겠네요

```js
this.(this.contestID ? contestAnnouncementList : this.announcementList).find(...)
```

2021-09-15 07:09 UTC, dotoleeoak commented on frontend/src/pages/oj/views/announcement/AnnouncementList.vue
> +        const res = await api.getAnnouncementList((page - 1) * this.limit, 250)
`this.limit`도 지워주세요

2021-09-15 10:53 UTC, DailyPS commented on frontend/src/pages/oj/components/CodeMirror.vue
> +  #codemirror::v-deep .CodeMirror-scroll {
이 부분은 좀 이상하네요. 원래 PR(#172)에서도 `scoped` 는 그대로 있습니다.

2021-09-15 11:08 UTC, dotoleeoak commented on frontend/src/pages/oj/components/CodeMirror.vue
> +  #codemirror::v-deep .CodeMirror-scroll {
@DailyPS 그럼 #172 말고 #75 인가보네요

2021-09-15 11:45 UTC, DailyPS commented on frontend/src/pages/oj/components/CodeMirror.vue
> +  #codemirror::v-deep .CodeMirror-scroll {
확인했습니다

2021-09-15 16:44 UTC, jimin9038 commented on frontend/src/pages/oj/views/problem/Problem.vue
> +        const lang = res3.data.data && res3.data.data.language
이거 좋네요

2021-09-15 17:46 UTC, jimin9038 commented on frontend/src/pages/admin/views/general/Announcement.vue
> +          this.contestAnnouncementList.find(item => {
방법은 괜찮은데 this.contestID 가 있을 때 dialog title을 'Edit Clarification'으로 바꾸는 게 좋을 것 같아서 그대로 두었습니다.

2021-09-15 18:34 UTC, jimin9038 commented on frontend/src/pages/oj/views/announcement/AnnouncementList.vue
> +        const res = await api.getAnnouncementList((page - 1) * this.limit, 250)
```javascript
async getAnnouncementList () {
    this.btnLoading = true
    try {
      const res = await api.getAnnouncementList(0, 250)
    ... 

```
으로 바꿨습니다.

2021-09-15 18:34 UTC, jimin9038 commented on frontend/src/pages/oj/components/CodeMirror.vue
> +  #codemirror::v-deep .CodeMirror-scroll {
scoped 지웁니다

2021-09-15 18:36 UTC, jimin9038 commented on frontend/src/pages/oj/components/CodeMirror.vue
> +  }
problem.vue 에 있는 
```css
* {
  font-family: 'Manrope', sans-serif;
}
```
요거 때매 `.Codemirror`를 inherit 받지 못하게 되어있네요. 
`.Codemirror *`로 했습니다.

2021-09-15 18:43 UTC, jimin9038 commented on frontend/src/pages/admin/views/problem/Problem.vue
> +      testcaseRender: true,
Testcase 관련해서는 제가 보는 것보다 @cranemont 한번 봐주시고 @dotoleeoak Request review 해주세요!

2021-09-15 23:14 UTC, dotoleeoak commented on frontend/src/pages/oj/components/CodeMirror.vue
> +  }
@jimin9038 노놉 아마 `scoped` syntax 때문에 적용 안됐을텐데 (`.Codemirror`가 `*`보다 specificity가 높아요) `.Codemirror *`에서 뒤에 *은 빼도 될거에요

2021-09-16 02:06 UTC, jimin9038 commented on frontend/src/pages/oj/components/CodeMirror.vue
> +  }
@dotoleeoak .Codemirror가 *보다 specificity가 높긴 한데 실제 글자들은 .Codemirror를 상속 받는 element이기 때문에 그런거 같네요 상속보다는 *가 우선 순위가 더 높죠

2021-09-16 06:15 UTC, dotoleeoak commented on frontend/src/pages/oj/components/CodeMirror.vue
> +  }
@jimin9038 찾아보니까 CodeMirror 최근 버전에서는 문서에 나온대로 폰트, 높이, 너비 같은건 `.CodeMirror`에만 적용해도 되는데 yarn.lock에서 의존하는 codemirror 버전이 구버전(5.59.2)이라 그런 거 같네요
일단 그럼 wildcard 붙여서 구현해주세요

2021-09-22 06:03 UTC, jimin9038 commented on frontend/src/pages/admin/views/problem/Problem.vue
> +      this.testcaseLoaded = false
testcaseLoaded는 로딩 중에 Submit 버튼이 눌리는 것을 막기 위해서 있는 것 같네요

2021-09-22 12:29 UTC, cranemont commented on frontend/src/pages/admin/views/problem/Problem.vue
> +          this.problem.testcases = null
File upload는 다른 API를 통해 별개로 이루어집니다. 해당 부분은 serializer에서도 받는 필드가 없어 필요없는 payload가 추가되는 듯하여 지웠습니다.

2021-10-30 07:08 UTC, minseo999 approved these changes

2021-10-30 09:08 UTC, dotoleeoak approved these changes

2021-10-30 09:11 UTC, merged