Implement oj page for Lecture Support Platform
skku-npc/skku-coding-platform pull request #235
Opened 2021-09-10 06:52 UTC by SOLBI1028

강의 지원 플랫폼 oj 페이지 구현
- Lecture List
- Lecture Assignment List
- Lecture Assignment Detail
- Lecture QnA
- Lecture QnA Detail

QnA 페이지는 퍼블리싱만 완료된 상태입니다

2021-09-10 09:30 UTC, dotoleeoak commented
1600줄이라니 😭😭😭

2021-09-23 16:23 UTC, jimin9038 requested changes

2021-09-23 16:23 UTC, jimin9038 commented on frontend/src/pages/oj/views/lecture/LectureList.vue
> +              {{ lecture.course.title }}
오타 고쳐주세요~

2021-09-23 16:23 UTC, jimin9038 commented on frontend/src/pages/oj/views/lecture/LectureList.vue
> +        this.showInformation = true
Remind..

2021-09-23 16:23 UTC, jimin9038 commented on frontend/src/pages/oj/views/problem/Problem.vue
> +      if (route === 'problem-details') {
다른 곳과 비슷하게 contest -> assignment -> problem 순서로 검사하면 좋을듯해용

2021-09-23 16:23 UTC, jimin9038 commented on frontend/src/pages/oj/views/problem/ProblemSidebar.vue
> +    this.submission_table_fields.unshift('Problem')
assignment나 contest일 때만 problem field 추가해줘야될듯 합니당

2021-09-24 07:53 UTC, SOLBI1028 commented on frontend/src/pages/oj/components/Header.vue
> +          <router-link class="nav-link" active-class="active" to="/lecture">Lectures</router-link>
이건 어제해서 커밋올려놓았습니당

2021-10-31 10:30 UTC, jimin9038 approved these changes

2021-10-31 10:32 UTC, minseo999 commented
oj 북마크 부분이 마무리가 안됐어요!

2022-01-12 13:20 UTC, jimin9038 approved these changes

2022-01-12 13:23 UTC, merged