Implement professor page for Lecture Support Platform
skku-npc/skku-coding-platform pull request #236
Opened 2021-09-10 18:12 UTC by jimin9038

Implementation of professor page for Lecture Support Platform

To be fixed issues..
1. 현재 새로고침시 404가 뜨는 이슈가 있어 파악중입니다.
2. Admin에서 가져온 components들 중 완전히 같은 것(codemirror, katexEditor, accordion 등,  panel, infoCard 제외)은 정리할 예정입니다.

2021-09-11 11:58 UTC, jimin9038 commented
9/11 Update
대시보드를 통해 들어갈 때 등의 상황에서 해당하는 route의 사이드바가 열리도록 추가

2021-09-23 13:59 UTC, SOLBI1028 requested changes

2021-09-23 13:59 UTC, SOLBI1028 commented on frontend/src/pages/prof/views/problem/ProblemGrade.vue
> +      utils.downloadFile(url)
await 붙여줘야 할 듯 합니당

2021-09-23 13:59 UTC, SOLBI1028 commented on frontend/src/pages/prof/views/problem/ProblemGrade.vue
> +    goCode (id) {
사용하지 않는 함수에요!

2021-09-23 13:59 UTC, SOLBI1028 commented on frontend/src/pages/prof/views/problem/ProblemGrade.vue
> +    currentChange (page) {
얘도 사용하고 있지 않습니당

2021-09-23 13:59 UTC, SOLBI1028 commented on frontend/src/pages/prof/views/users/UserList.vue
> +            this.selectedUserIDs.push(users.id)
40번째 줄 보면 checkbox는 registration_id기준인데, 여기서는 selectedUserIDs에 user id를 넣어서 select all이 정상작동하지 않은 것 같습니다! 
둘중 어떤걸 기준으로 할지 정해야 할 것 같아요
registration_id는 과목상관없이 모든 과목에서 사용자가 등록된 순서(149번째줄), user id는 가입순서에 따라 부여된 id인것 같은데, 둘중 어떤걸 기준으로 하는게 좋을까요?
아니면 과목별로 registration_id를 따로 설정하여 과목별 사용자 등록 순서대로 registration_id가 1,2,3, ...으로 표시되는것도 좋을 것 같습니다!

2021-09-23 13:59 UTC, SOLBI1028 commented on frontend/src/pages/prof/views/problem/Problem.vue
> +      disableRuleType: false,
584번째 줄에서 true로 바뀌고 그 이후로 사용되지 않습니다! 584번째 줄과 함께 지워도 될 것 같아요

2021-09-23 13:59 UTC, SOLBI1028 commented on frontend/src/pages/prof/views/problem/Problem.vue
> +    const res = await api.getLanguages()
이건 굉....................장히 사소한거긴한데,, 아래 583번째 줄에서 res가 사용되기도하고, 이 res가 587번째 줄에서 사용되어서요..! 586번째줄 밑으로 옮기는것이 어떨까요,,,,?

2021-09-23 13:59 UTC, SOLBI1028 commented on frontend/src/pages/prof/views/problem/Problem.vue
> +    async getProblemTagList () {
이 함수가 호출이 한번도 되지 않아요!
그래서 problemTagList에 생성된 태그 목록이 들어가지 않고, 태그를 등록해도 등록된 태그들이 dropdown 밑에 표시되지 않는 것 같습니다(193번째줄)

2021-09-23 13:59 UTC, SOLBI1028 commented on frontend/src/pages/prof/views/problem/Problem.vue
> +            file.score = (100 / fileList.length).toFixed(0)
submit버튼을 누를때 file.score가 100/testcase개수로 항상 등록되어서 testcase별 점수를 등록해도 다 무시되고 (100/testcase개수)가 되는 것같아요..! 입력받았을 경우에는 입력받은게 score가 되도록 해야할 것 같습니다.
그리고 위와같이 testcase별 score를 계산해서 testcase가 3개일때 각33점씩해서 총점이 99점이 됩니다..! 100으로 안나누어지는 testcase개수일때를 예외처리 해주어야 할 것 같아요!!

2021-09-24 00:19 UTC, y-jiu requested changes

2021-09-24 00:21 UTC, y-jiu commented on frontend/src/pages/prof/views/general/LectureBookmark.vue
> +              class="bookmark__btn"
사소한거긴 한데 class name에 underscore 을 두개 준 이유가 있나용?

2021-09-24 00:22 UTC, dotoleeoak commented on frontend/src/pages/prof/views/general/LectureBookmark.vue
> +              class="bookmark__btn"
그건 BEM architecture 참고해주세요
https://nykim.work/15

2021-09-24 00:24 UTC, y-jiu commented on frontend/src/pages/prof/views/general/LectureBookmark.vue
> +              class="bookmark__btn"
오 감사합니당!!

2021-09-24 03:58 UTC, minseo999 commented on frontend/src/pages/prof/views/users/UserList.vue
> +            this.selectedUserIDs.push(users.id)
저는 userlist에서 registration id 혹은 user id를 보여주지 않아도 될 것 같아요
(userlist에서 id를 보여주는 것이 사용자 입장에서 편리하다면, registration id나 user id가 아닌 인덱스(1,2,3, ...) 를 보여주는 것이 좋을 것 같습니다 -> 전체 학생 수 파악 정도의 역할로??)

2021-09-24 04:11 UTC, minseo999 commented on frontend/src/pages/prof/views/users/UserList.vue
> +            this.selectedUserIDs.push(users.id)
`deleteStudent` api를 호출할 때 user_id가 아닌 registration_id를 넘겨줘야하기 때문에 `selectedUserIDs` 배열에는 registration_id가 들어가는 것이 맞습니다

2021-09-24 04:21 UTC, jimin9038 commented on frontend/src/pages/prof/views/users/UserList.vue
> +            this.selectedUserIDs.push(users.id)
그러네용 사용자에게 보여줄 때는 registration id는 딱히 필요 없을 듯 하니 index로 하겠습니다

2021-09-24 04:24 UTC, minseo999 commented on frontend/src/pages/prof/views/problem/Problem.vue
> +    async getProblemTagList () {
admin 페이지의 Problem.vue 에도 이 코멘트 반영하면 좋겠네요 :)

2021-09-24 04:50 UTC, minseo999 commented on frontend/src/pages/prof/views/problem/Problem.vue
> +            file.score = (100 / fileList.length).toFixed(0)
assignment의 total_score는 항상 100으로 고정이라서 (100/testcase개수) 로 계산한 것 같은데
예외처리가 필요하겠네요!
- testcase의 개수를 총 합이 100이 되게 받도록 하기
- 사용자가 직접 testcase별 점수를 등록하도록 해서 총 합이 100이 되게 하기
지금 생각나는건 이렇게인데, 어떤 방식으로 해야할까요?

그리고 현재 testcase별 점수를 등록하는 기능이 없지 않나요?

2021-09-24 05:35 UTC, jimin9038 commented on frontend/src/pages/prof/views/problem/Problem.vue
> +            file.score = (100 / fileList.length).toFixed(0)
뭔가 건드려고 하는데 좀 무서운 부분이 있네요 이건 천천히 봐야할 것 같습니다

2021-09-24 06:03 UTC, jimin9038 commented on frontend/src/pages/prof/views/problem/Problem.vue
> +    async getProblemTagList () {
요것도 천천히 볼게용

2021-09-26 03:58 UTC, jimin9038 commented on frontend/src/pages/prof/views/problem/Problem.vue
> +            file.score = (100 / fileList.length).toFixed(0)
모달 띄워서 확인하는 방식으로 해결했습니당

2021-09-26 07:13 UTC, minseo999 commented
9/26 update
testcase score, tag list 기능 수정 사항

![image](https://user-images.githubusercontent.com/76725982/134797625-124902f7-ed80-4f16-8859-5a5c9f894658.png)
![image](https://user-images.githubusercontent.com/76725982/134797635-c0666211-a8a7-4dc3-9ae8-5993f14235b3.png)

2022-01-12 13:21 UTC, SOLBI1028 approved these changes

2022-01-12 14:14 UTC, y-jiu approved these changes

2022-01-12 15:12 UTC, merged