Handled issue 7
skku-npc/skku-coding-platform pull request #36
Opened 2021-01-25 05:08 UTC by 22222bh

유저  선호 언어 설정하는 방법
1) 프로필/세팅에서 Default programming language를 설정한다. (수동)
2) 코드를 제출하면, 그 다음부터는 해당 언어로 자동으로 설정이 되어있다.

2021-01-26 13:38 UTC, dotoleeoak requested changes
`languages` field 관해서 추가 정리 부탁드립니다

2021-01-26 13:38 UTC, dotoleeoak commented on OnlineJudge/submission/views/oj.py
> +        user_profile.save()
`UserProfile` 테이블에 `language` field는 다른 용도가 이미 있는 걸로 알고 있어요
(아마 영어/중국어 설정)

2021-01-26 13:38 UTC, dotoleeoak commented on OnlineJudgeFE/src/pages/oj/views/problem/Problem.vue
> +                    :languages="problem.languages"
줄 마지막에 공백?
eslint로 formatting 부탁드릴게요

2021-01-26 13:38 UTC, dotoleeoak commented on OnlineJudgeFE/src/pages/oj/views/problem/Problem.vue
> +                <Tag v-else type="dot" :color="submissionStatus.color">
이 부분은 어떤 기능 추가한건가요??

2021-01-26 13:38 UTC, dotoleeoak commented on OnlineJudgeFE/src/pages/oj/views/problem/Problem.vue
> +          })
좋습니다 ㅎㅎ

2021-01-26 13:38 UTC, dotoleeoak commented on OnlineJudgeFE/src/pages/oj/views/setting/children/ProfileSetting.vue
> +        ],
`languages` field를 아예 대체할거면 `i18n` 내용도 정리해야될 것 같습니다
(예: `i18n/index.js`에 `const languages` 지우기, `zh-CN.js`, `zh-TW.js` 삭제)

2021-01-27 07:44 UTC, 22222bh commented on OnlineJudge/submission/views/oj.py
> +        user_profile.save()
이 부분때문에 저번에 DM 드린거에요! 주영님이랑 얘기했었을 땐 중국어로 설정을 굳이 안해도 될 것 같아서 language field를 선호 언어 설정용으로 사용 했는데, 막상 생각해보니 없앨 필요까지 있나 생각이 들어서요. 어떻게 진행하는게 나을까요?

> `UserProfile` 테이블에 `language` field는 다른 용도가 이미 있는 걸로 알고 있어요
> (아마 영어/중국어 설정)

2021-01-27 07:47 UTC, 22222bh commented on OnlineJudgeFE/src/pages/oj/views/problem/Problem.vue
> +                <Tag v-else type="dot" :color="submissionStatus.color">
> 이 부분은 어떤 기능 추가한건가요??

isssue #11(Compile Error 시 "에러 내용 확인"을 위한 안내 추가) 해결한 부분인데, 아직 반영되지 않은 것 같습니다.

2021-01-27 07:48 UTC, 22222bh commented on OnlineJudgeFE/src/pages/oj/views/setting/children/ProfileSetting.vue
> +        ],
language field를 대체할지, 새로운 field를 만들지 정해지면 바로 수정하겠습니당

2021-01-30 11:27 UTC, Jeongcc commented
master 브랜치에 올라온 .github/workflows 포함해서 PR 다시 올려주세요!

2021-01-31 04:22 UTC, dotoleeoak commented
@Jeongcc @22222bh GitHub Action 포함 및 test 완료했습니다

2021-01-31 10:20 UTC, Jeongcc commented
Test Fail 이유 확인해주시고 Pass할 수 있도록 수정 부탁드립니다

2021-01-31 10:23 UTC, Jeongcc commented on OnlineJudgeFE/src/pages/oj/views/setting/children/ProfileSetting.vue
> +        ],
이 부분 27일 회의에서 language field 쓰기로 결정한 것 맞나요?

2021-01-31 16:28 UTC, dotoleeoak commented on OnlineJudgeFE/src/pages/oj/views/setting/children/ProfileSetting.vue
> +        ],
@Jeongcc 그냥 language field 써도 될 것 같아요
다만 꼼꼼이 확인한 다음에 merge할게요

2021-02-02 00:15 UTC, 22222bh commented
> Test Fail 이유 확인해주시고 Pass할 수 있도록 수정 부탁드립니다

@dotoleeoak @Jeongcc 늦게 확인했네요ㅜㅜ 수정하겠습니다

2021-02-02 02:29 UTC, closed without merging